### ISSUE TITLE
Last commit timeline mismatch

### ISSUE THREAD

**Issue by recap** [research-software-directory/RSD-as-a-service#1036]
On adding a new software with Git hub repository the timeline and last commit approximate months do not match.
<img width="978" alt="Screenshot 2023-11-01 at 06 35 05" src="https://github.com/research-software-directory/RSD-as-a-service/assets/2856084/c6b935ee-8026-418f-98bb-d93e89cc8b00">

**Comment by ewan-escience** [comment]
Thanks for reporting this. On which RSD page and for which Git repo is this?

**Comment by ewan-escience** [comment]
Looking at the picture again, the last commit seems to be from April 2022 (not 2023), in which case 19 months is a good estimate, right?

**Comment by ewan-escience** [comment]
This screenshot seems to be from the (unpublished) software page for https://github.com/dl4ld/petrinet. There have been commits in September 2023, but the API we use (https://api.github.com/repos/dl4ld/petrinet/stats/contributors) doesn't show this.

**Comment by ewan-escience** [comment]
I'm closing this, as the API delivers the data this way, so there is nothing we can do.
