### ISSUE TITLE
Highlight software planned soon?

### ISSUE THREAD

**Issue by elboyran** [research-software-directory/RSD-as-a-service#1047]
Several months ago, Jason told me that this feature is planned in the RSD release.

https://user-images.githubusercontent.com/1705533/230362191-3d18086b-5a15-483c-85f7-4ade721a8f76.png

Is this ending up as functionality in any planned RSD release before mid-January 2024?

If not, is there currently a way (preferably automated ;-) ) of making selected (aka "nominated" and labeled Software in the Spotlight) software appear in the first positions on the Software RSD page?

**Comment by elboyran** [comment]
I have found now a closed #932, but cannot see the feature in the RSD I'm running.

**Comment by ewan-escience** [comment]
The feature is there, but only admins can assign software highlights (currently there are none). It's best to contact @jmaassen to request software to be highlighted.

**Comment by jmaassen** [comment]
I discussed with @elboyran, so closing the issue.
