### ISSUE TITLE
Add data.europa.eu as DOI source?

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#1071]
I tried to add the publication 10.2777/28598 to the RSD but it seems this DOI is not registered in either DataCite or Crossref. 

The full URL is: 

https://data.europa.eu/doi/10.2777/28598

Could it be that the EU is minting their own DOIs without the metadata ending up in DataCite?

**Comment by dmijatovic** [comment]
Yes, as far as I understand the info

- To get RA (DOI Registration Agency) you can use DOI api https://doi.org/doiRA/10.2777/28598
```json
[
  {
    "DOI": "10.2777/28598",
    "RA": "OP"
  }
]
```
- Another endpoint can be used to get more info, https://doi.org/api/handles/10.2777/28598
```json
{
    "responseCode": 1,
    "handle": "10.2777/28598",
    "values": [
        {
            "index": 1,
            "type": "URL",
            "data": {
                "format": "string",
                "value": "https://op.europa.eu/publication/manifestation_identifier/PUB_KI0220998ENN"
            },
            "ttl": 86400,
            "timestamp": "2020-12-07T20:05:45Z"
        },
        {
            "index": 100,
            "type": "HS_ADMIN",
            "data": {
                "format": "admin",
                "value": {
                    "handle": "0.NA/10.2777",
                    "index": 200,
                    "permissions": "011111110010"
                }
            },
            "ttl": 86400,
            "timestamp": "2020-12-07T20:05:45Z"
        }
    ]
}
```

**Comment by ewan-escience** [comment]
It doesn't seem like the Publications Office of the European Union has an API.

However, we can use the OpenAlex API: https://api.openalex.org/works/https://doi.org/10.2777/28598
