### ISSUE TITLE
Add "support" for additional package managers

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#1081]
Based on current RSD data we should extend the package manager list with:

- Debian: https://packages.debian.org/search?keywords=libcdk-java
- Sonatype: https://central.sonatype.com/artifact/org.openscience.cdk/cdk-bundle/overview
- Chocolatey: https://community.chocolatey.org/packages/openchrom
- Snapcraft: https://snapcraft.io/openchrom
- Github: https://github.com/orgs/research-software-directory/packages?repo_name=RSD-as-a-service 
- Gitlab: https://gitlab.com/gitlab-org/gitlab/container_registry
- Rust: https://crates.io/crates/serde
- Go: https://pkg.go.dev/strconv

The ENUM in db should be extended with additional keys and the logos should be obtained from official sources.
Below is complete (new) list of package managers we "recognize" and the scraper services we support. If we do not have scraper service the services array is empty (no scrapers running).

**In addition, package manager data should be updated from 'other' to proper enum value after the upgrade**

## Updated package manager configuration object on FE

```Javascript
export const packageManagerSettings = {
  anaconda: {
    name: 'Anaconda',
    icon: '/images/anaconda-logo-96.svg',
    hostname: ['anaconda.org'],
    services: ['dependents']
  },
  cran: {
    name: 'CRAN',
    icon: '/images/cran-r-logo.svg',
    hostname: ['cran.r-project.org'],
    services: ['dependents']
  },
  chocolatey: {
    name: 'Chocolatey',
    icon: '/images/chocolatey-logo.svg',
    hostname: ['community.chocolatey.org'],
    services: []
  },
  debian:{
    name: 'Debian',
    icon: '/images/debian-logo.svg',
    hostname: ['packages.debian.org'],
    services: []
  },
  dockerhub: {
    name: 'Dockerhub',
    icon: '/images/dockerhub-logo.webp',
    hostname: ['hub.docker.com'],
    services: ['downloads']
  },
  github: {
    name: 'Github',
    icon: '/images/github-logo.svg',
    hostname: ['github.com'],
    services: []
  },
  gitlab: {
    name: 'Gitlab',
    icon: '/images/gitlab-icon-rgb.svg',
    hostname: ['gitlab.com','registry.gitlab.com'],
    services: []
  },
  maven: {
    name: 'Maven',
    icon: '/images/apache-maven-logo.svg',
    hostname: ['mvnrepository.com'],
    services: ['dependents']
  },
  npm: {
    name: 'NPM',
    icon: '/images/npm-logo-64.png',
    hostname: ['www.npmjs.com','npmjs.com'],
    services: ['dependents']
  },
  pypi: {
    name: 'PyPi',
    icon: '/images/pypi-logo.svg',
    hostname: ['pypi.org'],
    services: ['dependents']
  },
  sonatype:{
    name: 'Sonatype',
    icon: '/images/sonatype-logo.svg',
    hostname: ['central.sonatype.com'],
    services: []
  },
  snapcraft:{
    name: 'Snapcraft',
    icon: '/images/snapcraft-logo.svg',
    hostname: ['snapcraft.io'],
    services: []
  },
  other: {
    name: 'Other',
    icon: null,
    hostname: [],
    services: []
  }
}
```

**Comment by dmijatovic** [comment]
@jmaassen, @ewan-escience, @fembau, @cmeessen Do you have additional software downloading location, preferably based on data already present in RSD?

**Comment by cmeessen** [comment]
Every GitLab repository can have its own container or package registry:

https://docs.gitlab.com/ee/user/packages/

For example, we distribute the Helmholtz RSD images via our own [container registry](https://codebase.helmholtz.cloud/groups/research-software-directory/-/container_registries).
