### ISSUE TITLE
double entries in maintainer list

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#1091]
For many projects where i am maintainer , people are listed twice. Once with 'esciencecenter.nl' subscript, and once without.
For example, see [this project](https://research-software-directory.org/projects/diversity-aware/edit/maintainers).

Removing one of the duplicate entries removes *both* of them -- but please verify, i dont want to remove myself accidentally.

**Comment by ewan-escience** [comment]
Is this for maintainers who linked their ORCID account to their SURFconext account? Because I think we forgot to deduplicate there.

**Comment by jiskattema** [comment]
I can't help you here, except to add that i added my ORCID to my account, but i log in via SURFconext

**Comment by ewan-escience** [comment]
The problem here is in displaying the maintainers, as the backend (see e.g. [here](https://github.com/research-software-directory/RSD-as-a-service/blob/186dd74a910f2ade28139a26487e1b04ed690fb5/database/100-create-api-views.sql#L629)) returns for each account an array of associated login details.
