### ISSUE TITLE
Update documentation "Log in as RSD administrator"

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#1132]
For local development, and if the variable `RSD_ENVIRONMENT` has been set accordingly, the first user that logs into the RSD is the administrator.

The section [Log in as RSD administrator](https://research-software-directory.org/documentation/rsd-instance/getting-started/#log-in-as-rsd-administrator) needs to be updated accordingly.

**Comment by ewan-escience** [comment]
It is mentioned [here](https://github.com/research-software-directory/RSD-as-a-service/blob/main/authentication/README.md).

**Comment by cmeessen** [comment]
Yes, apologies for that. This issue can be closed.
