### ISSUE TITLE
Do not show software highlights section when javascript is disabled

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#1158]
Software highlights section uses Javascript for scroll navigation between items. When javascript is disabled complete section should not be hidden. Currently only title is shown without any functionality (see image)

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/742f92bc-5f8e-4dd0-8d1e-6a2635986600)

**Comment by ewan-escience** [comment]
The only reason this is not server side rendered is because in the file `frontend/components/software/overview/highlights/HighlightsCarousel.tsx`, the left padding is calculated on the client (see the variable `distance`). @ctwhome is there a way we can do with e.g. CSS only?

**Comment by dmijatovic** [comment]
This issue is handled in #1195 by not showing the software highlight section when JS is diasbled (see image). Css class is created `hide-on-no-script` to hide components that require javascript.

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/3f0a3e30-8f53-46cb-9d1f-69959d54859d)
