### ISSUE TITLE
Bug in organization releases overview when signed in

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#1163]
When I visit: 

https://research-software-directory.org/organisations/netherlands-escience-center?tab=releases

I get an overview of the software releases: 

![Screenshot 2024-04-10 at 14-28-42 Netherlands eScience Center Research Software Directory](https://github.com/research-software-directory/RSD-as-a-service/assets/1705533/95ca9c71-8f13-4d23-bb0a-7f729271bba5)

When I sign in, I get different results. This could be due to unpublished software (which is fine): 

![Screenshot 2024-04-10 at 14-29-50 Netherlands eScience Center Research Software Directory](https://github.com/research-software-directory/RSD-as-a-service/assets/1705533/db92d470-e2e8-4487-a2a0-151d14c6e151)

However, when I start clicking on different years, the "I-Vresse bartender" software shows up on top of the list, regardless if it is the correct year. The number of "I-Vresse bartender" entries also grows every time I select a different year: 

![Screenshot 2024-04-10 at 14-32-10 Netherlands eScience Center Research Software Directory](https://github.com/research-software-directory/RSD-as-a-service/assets/1705533/c7362cc4-cf1b-4a1d-b869-3a552bd3c83b)

**Comment by ewan-escience** [comment]
I also see wrong entries (i.e. having a different year) when not logged in when switching between years.

**Comment by ewan-escience** [comment]
I think it has to to with the key used in the underlying React component, because I get this warning in the console:

```
Warning: Encountered two children with the same key, `10.5281/zenodo.7614738`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

If I chage the `key` in [line](https://github.com/research-software-directory/RSD-as-a-service/blob/a268adb128b0bf813620ea9a1d3c44ede37a715e/frontend/components/organisation/releases/ReleaseList.tsx#L55) to just `pos`, it seems to work.

**Comment by ewan-escience** [comment]
The underlying data issue is that there are two software pages, one published and one unpublished, both called `i-VRESSE bartender`, with the same concept DOI. As admin, you also get to see the releases of the unpublished entry, resulting in a duplicate `key` as in my message above.
