### ISSUE TITLE
Highlights carousel doen't have touch support for Firefox

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#1181]
On my laptop with a touch screen, I cannot swipe through the highlights on Firefox, while I can on Chromium.

**Comment by dmijatovic** [comment]
Maybe specific "personal" issue? Touch works when using FF and the mobile emulator in developers console on my machines (but I have touch screen). Let see if more people facing this issue.

**Comment by ewan-escience** [comment]
Indeed, I can also use it in the developer console. For desktop, you apparently have to follow the instructions [here](https://old.reddit.com/r/firefox/comments/c9hsvr/psa_enable_touchscreen_gestures_in_linux_firefox/) (which I'm not gonna do, because it requires editing a conf file and rebooting). I'm gonna assume it works properly now, we can reopen this issue if anyone does have this problem.
