### ISSUE TITLE
Upgrade eslint naar v9 and setup prettier

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#1198]
We should upgrade eslint to v9 and use prettier as formatter. 

Currently we use eslint for both linting and formatting. 
The formatting rules will be [removed from eslint in the future](https://eslint.org/blog/2023/10/deprecating-formatting-rules/). 

We will need to update eslint and configure prettier.

**Comment by ewan-escience** [comment]
A migration guide can be found [here](https://eslint.org/docs/latest/use/migrate-to-9.0.0). Notable is that the configuration format has changed, for which a [migration quide](https://eslint.org/docs/latest/use/configure/migration-guide) exists as well.

**Comment by ewan-escience** [comment]
Since 14 October, the [issue for Eslint 9 and Next.js](https://github.com/vercel/next.js/issues/64409) has been resolved, so we could have another try,
