### ISSUE TITLE
Categories dropdown shown when there are no categories to select

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#1251]
In the software edit view, the categories dropdown is shown when there are no categories defined:

![image](https://github.com/user-attachments/assets/3a1b4a1b-525c-480d-82ff-b50b0cd42ca1)

This dropdown is also shown, if only "highlighted" categories are defined.

Apart from that, the headline is not bold, unlike the other headlines. The `EditSectionTitle` in `AutosaveSoftwareCategories` is missing the `font-medium` class.

**Comment by ewan-escience** [comment]
Would you prefer to not have the section or to have a message saying there are no categories to choose from? @jmaassen what do you think?

**Comment by cmeessen** [comment]
I would prefer to not show the section at all.
