### ISSUE TITLE
Scrape citations of reference papers with an OpenAlex ID

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#1291]
Some reference papers, like [this one](https://europepmc.org/article/PMC/8075508), from [Vantage6](https://research-software-directory.org/software/vantage6), do have an [OpenAlex ID](https://api.openalex.org/works/W3159002838) but *don't* have a DOI. We should be able to scrape citations from those papers as well.

**Implementation notice**: it might be necessary to create a dedicated field for the OpenAlex ID in the database.

**Comment by Gerib0y** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer
