### ISSUE TITLE
Zotero and earlier RSD legacy issues 

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#1295]
Just wanted to bring this one to attention. 

When we did import from Zotero to RSD, and also from earlier versions of RSD, the following issue occurred.

@sonjageorgievska remarks that

> The issue is that for most of our tools, their "reference" papers were previously listed under the "mentions" section. However, it is typically the reference paper that receives a citation when the tool is used, while the DOI on Zenodo is rarely cited by researchers.
>  Recently, a new "reference paper" feature was added to the RSD, but this only applies to newer tools, meaning many older tools still don't have a properly designated reference paper in the RSD, out of which the impact could be tracked.

Is there any way to solve this? Any way to identify what was automatically harvested and what was there prior to automatic harvesting?

**Comment by ewan-escience** [comment]
I don't think we can easily identify that. But would it help to see what software doesn't have a reference paper yet? You can see that [here](https://research-software-directory.org/api/v1/software?select=slug,brand_name,reference_paper_for_software(*)&reference_paper_for_software=is.null).

**Comment by bakhshir** [comment]
So, if i understand correctly you suggest to trace the projects missing output which is around software via respective software RSD page?

**Comment by ewan-escience** [comment]
This was discussed and resolved internally.
