### ISSUE TITLE
categories: the order of appearance

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#1348]
The (sub)categories are appearing in the random order. For example, if i add new infra subcategory to this page: https://research-software-directory.org/projects/recruit I cannot decrypt in which order this is appearing (see attached screenshot) Does it try to find most compact way of displaying subcategories?

![image](https://github.com/user-attachments/assets/daf54cac-d232-42e1-9f4c-c640856830b9)

**Comment by dmijatovic** [comment]
We do not apply any ordering currently, so the items are now listed at random. I think alphabetical order of items ("chips") withing a category group would be more logical.
