### ISSUE TITLE
Cannot read commit history

### ISSUE THREAD

**Issue by Peter9192** [research-software-directory/RSD-as-a-service#1357]
I created https://research-software-directory.org/software/cityblocks and it states that it cannot read the commit history

![image](https://github.com/user-attachments/assets/76d8ed81-cb75-4f3c-a9e1-6ff2e5c8fa5c)

Why is that?

**Comment by jmaassen** [comment]
The github API we use to retrieve this information (in this case: https://api.github.com/repos/Urban-M4/cityblocks/stats/contributors) does not always return an answer. Sometimes calling it only triggers some task at github to start gathering this information and generate the necessary statistics. 

This is equivalent behavior to clicking on the contributors link an a github page (i.e., https://github.com/Urban-M4/cityblocks/graphs/contributors) and getting the "loading" swirl with the message that they are preparing the info. 

This issue will fix itself once github is done producing statistics and the API starts giving us a response. 

The other time I've seen this happen is with software where the information on the contributors isn't public (i.e., their user account isn't publicly visible). In that case, we can see the software, but the github API does not want to tell us which contributions a user made. 

I'm not sure if we can tell the difference between "working on it" and "no information available". If so, we could improve the message on the RSD a bit. We'll look into this.

**Comment by Peter9192** [comment]
Thanks for the explanation! The commit history is visible now, so I'll close this.
