### ISSUE TITLE
Move external httpsRequests (often database calls and other services) into 'api' folder

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#140]
Separation of concerns is very important when developing Web Applications. We are already extracting the external logic from components. I propose to have a minimal restructure for the frontend folder (mainly API folder) where the external API calls are grouped into an API folder.

See the example below, it doesn't have to be exactly the same but I would like to have an API folder to clearly distinguish those functions that make external calls. The sooner we make it, the better. Refactoring a full application in the future will probably never happen, hurting the development experience.

[Post reference here](https://dev.to/larswaechter/how-i-structure-my-react-projects-jii)

## Directory: root

```
react-project
├── node_modules
├── public
├── src
├── package.json
└── package-lock.json
```

## Directory: src

```
react-project
├── api
├── components
├── i18n
├── modules
├── pages
├── stores
├── tests
├── utils
├── index.js
├── main.js
└── style.css
```

## Directory: src/api

```
react-project
├── api
│   ├── services
│   │   ├── Job.js
│   │   ├── User.js
│   ├── auth.js
│   └── axios.js
```

**Comment by jmaassen** [comment]
Close for now
