### ISSUE TITLE
Log scraper errors and report them

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#171]
The scrapers run in the background to collect various information about the software. They use information provided by software maintainers as initial input. This information might be incorrect or insufficient or there might be some other problems during the scraping process. The maintainers need to be notified about these errors. 

I propose to create logs table with the following props:
- id (uuid)
- software (uuid)
- service (scraper/service name)
- message: error message
- created_at (timestamp)

We can shown this information in the edit software section, based on software uuid), so the maintainers are aware of the failures.

**Comment by jmaassen** [comment]
Maybe we should also be able to report on dead links in the pages, for example project links?

**Comment by ewan-escience** [comment]
With #928, the database and scrapers have been adapted. We still need to adapt the frontend to show the short error messages to the maintainer and to show the full backend logs to the admint.

**Comment by ewan-escience** [comment]
With #1070, this is now completed.
