### ISSUE TITLE
docker-compose has issues finding lowercase dockerfiles

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#174]
I was following the build instructions and ran

```
docker-compose build
```

which got stuck with the following error messages:

```
5 errors occurred:
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/chmee/git/RSD-as-a-service/scrapers/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/chmee/git/RSD-as-a-service/nginx/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/chmee/git/RSD-as-a-service/database/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/chmee/git/RSD-as-a-service/backend-postgrest/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/chmee/git/RSD-as-a-service/authentication/Dockerfile: no such file or directory
```

The Dockerfiles in these directories exist, however, they are written lowercase `dockerfile`, which is why docker-compose doesn't find them. If I rename the Dockerfiles to `Dockerfile`, the build process works fine. I noticed that some Dockerfiles are written as `Dockerfile` too, which I think is the [convention](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) for Dockerfiles. If nothing speaks against it I would create a pull request where we rename the Dockerfiles.

I am running on Manjaro Linux using Docker version 20.10.12 build e91ed5707e, and docker-compose version 2.3.3.

**Comment by ewan-escience** [comment]
Interesting error, none of us has experienced this. But please go ahead and change the capitalisation, it is good to be consistent and to follow the convention.

**Comment by cmeessen** [comment]
Thanks, I am going to open the PR soon but am not sure whether I ran all the tests correctly. Is there a single command to run all of them at once? I manually ran the tests from `tests_main.yml`:

```
cd frontend
yarn test:coverage
cd ../backend-postgrest/tests
docker-compose up --abort-on-container-exit --exit-code-from-postgrest-tests
```

**Comment by ewan-escience** [comment]
That seems fine. We don't have a single command to run all tests. When you build the frontend through `docker-compose`, the frontend tests are also executed. And when you open a PR, tests are also run, depending on what changed.
