### ISSUE TITLE
Pull authors from zenodo

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#201]
Message from Peter 

Hi, I was adding my software to the RSD, but wondered whether filling some of the information could not have been done automatically. After having it filled in for the citation.cff and on Zenodo, I needed to fill in things like the contributors again in the RSD. Would be nice if this could be somehow synchronized maybe?

**Comment by cmeessen** [comment]
We have this one planned in research-software-directory/Helmholtz#9
