### ISSUE TITLE
Employees from the three participating organisations should be able to register and login

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#21]
All employees from the three participating organisations should be able to authenticate themselves to the RSD. This should be possible with their OpenID provider (unknown at this time).

**Comment by jmaassen** [comment]
Working on Leiden. Others will follow.

**Comment by ewan-escience** [comment]
It already works for Utrecht.

**Comment by jmaassen** [comment]
Mostly done. AMC is waiting for someone to flip the switch
