### ISSUE TITLE
Create theme engine 

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#210]
We are currently supporting light and dark theme for the new branding, see the new landing page.
 We need to provide a way to theme the styling via configuration files.

One way to do it is using css variables to provide generic utility classes such as "base-100" "base-200"

## to do
- [ ] create base utility classes
- [ ] document how themes work
- [ ] theme switcher provider
- [ ] set css variables from a configuration file

## References
- DaisyUI utility helpers design (tailwindcss plugin)

**Comment by dmijatovic** [comment]
@ctwhome I think we should use material ui theming engine, which is already available in the project and supports dynamic theme change at runtime.

**Comment by jmaassen** [comment]
Followed up by #410
