### ISSUE TITLE
Load colors from config for MUI dark theme

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#214]
Currently components on software and project page use custom color which is hardcoded in the Mentions components. The colors should be loaded from the config file for dark theme. 

![image](https://user-images.githubusercontent.com/9204081/162984333-634a8de8-f1ae-46ce-b74c-3d887e8c8304.png)

**Comment by ctwhome** [comment]
I agree that the colors should not be hardcoded, but rather than getting the styles from a 'dark' theme, we need to set up a way to only have one theme at a time. With different color blocks and contrasts, but only one theme.
