### ISSUE TITLE
Mention styling issues

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#218]
While testing the new homepage & style I noticed several small issues with the mentions block which could be improved: 

- The text in the mention block seems to be stuck to the left of the bar. It would look cleaner if there was more space on the left of the text. 

![mentions](https://user-images.githubusercontent.com/1705533/163120197-e4cb5ab8-b7d1-44d1-b5a4-dc10261e8d9f.png)

- The "counter bubbles" stand out too much due to their different color and position. I think it would be cleaner if they would be in front (like in the legacy RSD) and have a less contrasting color? Maybe even the same color as the rest, for example: 

![mentions-new](https://user-images.githubusercontent.com/1705533/163121736-b39e9318-2fee-47df-9187-5da0fd7561d3.png)

**Comment by dmijatovic** [comment]
@jmaassen I work on issue #214 that improves theme integration. The change result in the following layout

![image](https://user-images.githubusercontent.com/9204081/163129962-7e30c197-4966-452c-af33-4b50d8d39a8a.png)

Let me know if you would like to change more. I think this is nice design but this my personal opinion. For using simple number I would advice to place numbers after the category.
