### ISSUE TITLE
Lighthouse audit - frontend performance and improvement suggestions

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#228]
# Lighthouse improvement suggestion

There is been some time since we run the Lighthouse audit. New pages are added and the features were extended. I just run the audit again on new pages and these are the scores. When we have time we can work on improvements.

## Home page

![image](https://user-images.githubusercontent.com/9204081/163421069-1689a44c-cff1-4941-8d97-918d6d7b8806.png)

## Software
![image](https://user-images.githubusercontent.com/9204081/163421276-454d0a20-e233-4cfa-b680-b7453fb838f7.png)

## Software item
![image](https://user-images.githubusercontent.com/9204081/163421538-f426b79a-05e3-4fe0-af82-308166c813f0.png)

## Projects
![image](https://user-images.githubusercontent.com/9204081/163421686-10dac797-859a-4475-819b-ffe5ca778f10.png)

## Project item
![image](https://user-images.githubusercontent.com/9204081/163421864-fb0b4988-a384-4255-b731-4857bba289e2.png)

## Organisations
![image](https://user-images.githubusercontent.com/9204081/163421990-dffefa9b-03ef-4c54-9df4-762062e0e7fe.png)

## Organisation item
![image](https://user-images.githubusercontent.com/9204081/163422170-88027767-649d-4ac5-ab26-bf8f60cb4194.png)

**Comment by ctwhome** [comment]
These numbers are brilliant, we could test them later against the online VM
as well, tho o don't expect bigger differences!
