### ISSUE TITLE
Improve counters on landing page

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#238]
At the moment, the landing page has dummy counters:

![Screenshot_2022-04-26_13-46-09](https://user-images.githubusercontent.com/1705533/165293199-d9f1027e-ac57-41aa-a320-40f6a80f7e25.png)

could these be replaced with the actual counts? And add `projects` to the list?

**Comment by ewan-escience** [comment]
Replace researchers with projects. Order should be software, projects, organisations.
