### ISSUE TITLE
Detect and convert relative image paths in external Markdown

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#249]
On software pages, for the description you can point to an external Markdown file. This works mostly fine, except when the file contains relative paths to images. Can we detect when relative paths are used and can we convert them to absolute paths on the fly?

**Comment by jmaassen** [comment]
This is difficult to do. Would be better to encourage people to improve their markdown files.

**Comment by jmaassen** [comment]
Should add instruction on how to improve to documentation.
