### ISSUE TITLE
Maintainer flow improvements

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#260]
We should consider the following improvements to the maintainer flow:

- invitations should have an expiration date, a maximum validity period (e.g. 1 week) should be enforced
- it should be possible to see invitations (and who accepted them)
- it should be possible to delete/retract unused invitations (implemented in #485)
- expired unused invitations should regularly be cleaned up from the database
- maybe used invitations should be cleaned up as well
- show the error messages from the database on failure instead of the generic message (implemented in #258)

**Comment by jmaassen** [comment]
Let's cleanup the used invites after 1 month. The unused ones may have an expiry date shown or "expired" when unused for too long. A month after expiration they are also cleaned.
