### ISSUE TITLE
Editing imported keywords

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#273]
## Feedback received on first import keywords version

Works like a charm, thank you @dmijatovic and @ruester :)

There is one thing I am still thinking could be added, when I see the NASA GCMD Keywords from the Riesgos publication: an edit button for the imported keywords that lets you change the keywords inside the badges. But I don't want to intervene in merging, we could create a new issue for that.

**Comment by ewan-escience** [comment]
Since you can delete the imported keywords and add your own, we decided to not do this.
