### ISSUE TITLE
Move Hotjar configuration into environment file

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#276]
With the current implementation of Hotjar, the configuration is hard coded. This implies that all data is streamed to your Hotjar instance.

We would like to propose to make the usage of Hotjar configurable via the environment file.

The idea is to add a variable `HOTJAR_ID`. If the variable is defined, the Hotjar script will be added to the frontend using the given ID. If the variable is unassigned, Hotjar would not be added.

@dmijatovic @ctwhome @jmaassen what do you think? @ruester would implement the changes.

**Comment by dmijatovic** [comment]
Excellent idea! Same goes for the implementation! I approved it and would like to merge it tomorrow by noon. If anyone else would like to take look at PR #277, please do tomorrow.
