### ISSUE TITLE
User profile - personal info

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#284]
Show personal information of logged in user. Current info shown on the page is extracted from the token. Additional info is available in the `login_for_account` table.

- There is no design for this section. 
- Create api call to login_for_account using postgrest
- Show, name, email and home_organisation information of the user

For now we should only show the user information: name, email, organisation. This information originates from the login provider (IdP) and I am not sure if we shold let user change it.  For later we can enable adding additional emails, maybe upload the image. 

**I think we should discuss these options.**

## Starting position

![image](https://user-images.githubusercontent.com/9204081/169477239-7cd49d85-bdf6-4263-8dad-138ed2b94e2e.png)

**Comment by dmijatovic** [comment]
@ctwhome, @ewan-escience, @jmaassen, @cmeessen What shell we do with this section at the moment? I have put my suggestions in the issue. What do you think?

**Comment by ctwhome** [comment]
I am currently working on this
