### ISSUE TITLE
Create software citations scraper based on DOI

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#289]
We can scrape "official" citations of software done using DOI.

This service is offered by DataCite and intergrates citations done in DOI registered at Crossref.

In the DataCite "work" object there is a citations property that will show any citations done by other publications (DOI's).
As the citation of software can be done on "concept DOI" and per version the scraper should scrape the information from concept DOI and all related version DOI's.

## How to determine the concept DOI?
The concept DOI would have no values in the versionOf array, and will have DOI values in the versions object

## Example query 
In this example there is one citation

```GraphQL
query{
  work(id:"10.5281/zenodo.1051064"){
      doi,
      type,
      titles(first:1){
        title
      },
      citationCount
      versionCount,
      versionOfCount,
      versions{
        nodes{
          doi
        }
      },
      versionOf{
        nodes{
          doi
        }
      },
      citations{
        nodes{
          doi
        }
      }
    }
}
```
Add this query in the [GraphQL interface](https://api.datacite.org/graphql)

## Bonus service: extract image from meta tags on the webpage

In RSD we have featured flag that shows mention in the different format, with an image. Maybe we can scrape the image from the DOI page using meta tags.

![image](https://user-images.githubusercontent.com/9204081/170233586-a52a5712-9bee-42e4-b691-0a119a114959.png)

### Possible meta tags for extracting image
- og:image
```html
<meta property="og:image" content="https://media.springernature.com/w200/springer-static/cover/journal/12859.jpg">
```
- twiiter:image
```html
<meta property="twitter:image" content="https://media.springernature.com/w200/springer-static/cover/journal/12859.jpg">
```
- ...others ?

**Comment by ewan-escience** [comment]
[OpenAlex](https://openalex.org/) looks promising. Suppose we want to find the citations of the paper [Kernel Tuner: A search-optimizing GPU code auto-tuner](https://doi.org/10.1016/j.future.2018.08.004). We can find it in the OpenAlex database, using its DOI, with the following query:

https://api.openalex.org/works?filter=doi:10.1016/j.future.2018.08.004

The response contains a property called `cited_by_api_url`, which contains a link to https://api.openalex.org/works?filter=cites:W2887327791, which we can inspect further rusing [pagination](https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/paging).

Just like [CrossRef](https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service), OpenAlex supports a [polite pool](https://docs.openalex.org/how-to-use-the-api/rate-limits-and-authentication#the-polite-pool) for better reliability.

**Comment by dmijatovic** [comment]
> [OpenAlex](https://openalex.org/) looks promising. Suppose we want to find the citations of the paper [Kernel Tuner: A search-optimizing GPU code auto-tuner](https://doi.org/10.1016/j.future.2018.08.004). We can find it in the OpenAlex database, using its DOI, with the following query:
> 
@ewan-escience Can we check if both api's produce the similair results, eq. the same citations are discovered by both services? In that case we can select one we preffer, otherwise we might need to consolidate results from different services.

**Comment by ewan-escience** [comment]
DataCite doesn't have papers, so it returns nothing for the Kernel Tuner example. OpenAlex doesn't seem to have software (https://api.openalex.org/works?filter=doi:10.5281/zenodo.1051064 and some other examples return nothing), so we might have to combine the two of them.
