### ISSUE TITLE
Adding license information to all files

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#293]
Following my question from the last weekly, I would like to open this issue to discuss how license information could be enhanced in the repository.

I think that a very nice approach is used by the [REUSE Specification](https://reuse.software/). They provide a tool that can automatically add license and copyright information. It can be implemented via [pre-commit hooks](https://reuse.software/dev/#pre-commit-hook) to make it easy for the developers. Also, they have a linter that can be integrated in a [pipeline](https://reuse.software/dev/#ci) to check conformity.

This is an example for a license header from their page:

```
# SPDX-FileCopyrightText: 2016, 2018-2019 Jane Doe <jane@example.com>
# SPDX-FileCopyrightText: 2019 Example Company
#
# SPDX-License-Identifier: GPL-3.0-or-later
```

There is one drawback as far as I see: REUSE requires that licenses are placed in a `LICENSES` folder in the root of the directory. It makes sense in a way that here you can put multiple license texts, e.g. if texts or images have a `CC-BY` license. But in doing that, GitHub does not automatically detect the license anymore. But this may not be the case in the future anymore, since there are some [requests](https://github.com/licensee/licensee/issues/490) in the licensee repository that ask for REUSE support and the maintainer is open for that.

REUSE supports a machine readable [debian copyright](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0) file under `/.reuse/dep5`. That makes it easy to initially apply a license and copyright to all the files. However, as far as I could see, this cannot be automated, and it becomes tedious to take care about multiple copyright holders for individual files.

Finally, REUSE is also supported by the best practices badge mentioned in #153, and adding license/copyright info on a per file level is part of the "Gold" level.

/edit: my suggestion is to use a script to add the initial copyright statements. This would include:

* Copyright to all files for the NLeSC
* Add copyright of all authors that edited the specific files
* Add license statement
* Add a section to CONTRIBUTING and the documentation about how to configure your git to automatically add this info

@jmaassen @dmijatovic @ewan-escience @ctwhome would you be happy with this solution? I'd be happy to do the implementation for this.

**Comment by cmeessen** [comment]
I just realised that this would add me and the GFZ as a contributor to each file. That's a bit overdone from my point of view. I already created a script for this because we may need it in other repositories in the future too, and I would gladly provide it to the person who will do the commit and PR.

**Comment by ruester** [comment]
@cmeessen 
I have a problem with `frontend/next-env.d.ts` getting changed automatically if I run `yarn dev` and then being in the `git diff`, thus could lead to committing it accidentally.. the comment in the file also states that this file should not be changed:

> // NOTE: This file should not be edited
> // see https://nextjs.org/docs/basic-features/typescript for more information.

```bash
$ git diff
# empty
$ yarn dev
$ git diff
diff --git a/frontend/next-env.d.ts b/frontend/next-env.d.ts
index 39452d7..4f11a03 100644
--- a/frontend/next-env.d.ts
+++ b/frontend/next-env.d.ts
@@ -1,8 +1,3 @@
-// SPDX-FileCopyrightText: 2021 Dusan Mijatovic (dv4all)
-// SPDX-FileCopyrightText: 2021 dv4all
-//
-// SPDX-License-Identifier: Apache-2.0
-
 /// <reference types="next" />
 /// <reference types="next/image-types/global" />
```

Could we change it to have a `next-env.d.ts.license` file instead? Or maybe even remove and ignore the file completely as it seems to be automatically generated every time I start `yarn dev`? (CC @dmijatovic)

**Comment by dmijatovic** [comment]
@cmeessen and @ruester Yes, I noticed the same this morning. Not sure what we can do. Next uses this file and it seems to overwrite it with default values if it not what it is expected to be.

**Comment by dmijatovic** [comment]
@cmeessen and @ruester I think we can use separate license file. I just tested it locally and it seems to work. I can push fix here if you want to check. Basically follow the same approach as with image file.

**Comment by dmijatovic** [comment]
@ruester @cmeessen this is actually so annoying to me that I have already created license file. The fix, using license file will be included in mijn next PR.
