### ISSUE TITLE
Adding new item in mentions: store values entered in form fields when closing the form

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#299]
This issue relates to the features implemented with #295.

When adding a new mention using the "Create new item" window, this window can be closed when clicking on the greyed-out background.

If the window is closed, all unsaved data entered in the form beforehand is lost. Storing these values may improve the user experience after accidentally closing the window, because the user may not have to enter the data again.

/cc @dmijatovic

**Comment by dmijatovic** [comment]
@cmeessen I have disabled closing the modal on "backdropClick" / click away. The user can close modal using "esc" on keyboard or cancel button. This is implemented in #274.

We could save data from te form in the localStorage and reload it on the next opening. However I am not sure that would be the most viable use case. I do expect that from 10 processing, 9 times you want to start with new entry and not resume the previous one you accidentally closed/lost. 

I need some additional thinking about the flow...when to save data. Any suggestions are welcome. We can leave this issue open for further improvements

**Comment by cmeessen** [comment]
I think with #274 implemented, we can close this issue and refer to it again, if this feature should be integrated at some point.
