### ISSUE TITLE
Adding mentions from DataCite/CrossRef using publication titles: sort output by best match

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#300]
This issue refers to the features implemented with #295.

When adding a mention by searching for the title of a publication in DataCite/CrossRef, the list that is shown does not always put the best fitting result at the top of the list.

For example, searching for "The thermal and rheological state of the Northern Argentinian foreland basins" will place the object with this title somewhere in the middle.

Sorting by the best matching result (maybe the edit-distance may be useful here?) would help the user to more quickly find the desired result.

/cc @dmijatovic

**Comment by dmijatovic** [comment]
@cmeessen I managed to add basic order on search value in #274. You can test it if you want. Another addition in that PR is to disable closing the modal on "backdrop" click. You can close the modal using esc or cancel button.

**Comment by cmeessen** [comment]
:+1: both additions work perfectly, thank you!
