### ISSUE TITLE
Mention journal / venue / booktitle is missing

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#304]
When showing the mentions, the title, authors, publisher etc. is shown, but the name of the entity in which is was published is missing. For example, for the DOI [10.1016/j.diin.2018.09.002](http://dx.doi.org/10.1016/j.diin.2018.09.002) is shows: 

![cite](https://user-images.githubusercontent.com/1705533/171349064-8abc9dd5-3b6a-4f27-9b08-21137fb7268d.png)

while I would expect something similar to what crossref shows: 

![cite2](https://user-images.githubusercontent.com/1705533/171349090-3de48f37-9ae9-4a11-a90b-29f4687b981d.png)

or a more condensed version like researchgate: 

![cite3](https://user-images.githubusercontent.com/1705533/171349122-9cb8168c-1979-40e2-92ce-fc4562731aec.png)

Note that these typically do not show the name of the publisher (Elsevier BV), but do mention the name of the journal (Digital Investigations) and the volume (27), which is more informative. 

I can provide similar examples for conferences and book chapters. 

### Journal articles 
- Crossref:
    -  `container-title` property can be used to obtain journal name 
    -  `volume` can be used to obtain issue number / volume number
    -  `article-number` can be used if no page is provided

### Book chapter
- Crossref:
   -  `container-title` property can be used to obtain book title. It is array of strings. In this example 10.1007/978-3-030-14350-3_5  book title is first item and second value seem to be book serie title

**Comment by jmaassen** [comment]
Interestingly, crossref and researchgate show a different data (Dec 2018 vs Sept. 2018). The december one is correct: 

https://www.sciencedirect.com/science/article/pii/S174228761830149X?via%3Dihub

**Comment by dmijatovic** [comment]
@jmaassen Yes, please provide examples for conferences and book chapters and other publication types where the publisher is not the correct property to extract. We need to find where this information is stored. There are multiple endpoints where this info probably can be found and it helps if we have real examples and values to verify which property should be extracted.

**Comment by jmaassen** [comment]
An example for a conference paper is this one:  [10.1109/escience.2018.00013](https://doi.org/10.1109/escience.2018.00013)

Which you can find on crossref here:  https://search.crossref.org/?from_ui=yes&q=10.1109%2Fescience.2018.00013
and the publisher here: https://ieeexplore.ieee.org/document/8588632

Normally you would cite it in a similar way to this: "Proceedings of the 14th IEEE International Conference on e-Science (e-Science), 2018" or shorter: "2018 IEEE 14th International Conference on e-Science (e-Science)"

**Comment by jmaassen** [comment]
Example book section: [10.1007/978-3-030-14350-3_5](https://doi.org/10.1007/978-3-030-14350-3_5)

Currently the title doesn't show the book title. Crossref show this title here: 
https://search.crossref.org/?q=10.1007%2F978-3-030-14350-3_5&from_ui=yes

and cites it as "Book Chapter published 2020 in Recent Advances in Intelligent Engineering on pages 81 to 110"

Publisher page can be found here: 
https://link.springer.com/chapter/10.1007/978-3-030-14350-3_5
