### ISSUE TITLE
FAIR check fails because it does not recognise the license

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#322]
Since #293 the FAIR pipeline fails, because it does not find a LICENSE in the repository metadata.

This can be fixed by using a configuration file for the `howfairis` tool.

**Comment by jmaassen** [comment]
Shall I create an issue in the `howfairis` repo requesting support for the reuse licensing specification?

**Comment by cmeessen** [comment]
> Shall I create an issue in the howfairis repo requesting support for the reuse licensing specification?

Yes, I think that would be a good idea.

**Comment by cmeessen** [comment]
I created an issue in the howfairis repo: https://github.com/fair-software/howfairis/issues/362

**Comment by ewan-escience** [comment]
The action only fails because the current badge in the README does not match the badge we should have, see [this comment](https://github.com/fair-software/howfairis/issues/139#issuecomment-773173887).
