### ISSUE TITLE
Editing software mentions: Category transparent in Firefox

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#324]
In the mention edit view, the mention category (e.g. "Journal articles") appears transparent in Firefox (version 101.0.1 und Linux) when scrolling down:

![image](https://user-images.githubusercontent.com/14222414/173311645-0c982706-265d-47f7-9b04-8e637e4e7f9b.png)

/cc @dmijatovic

**Comment by dmijatovic** [comment]
@cmeessen Thanks! I will try to address it asap
