### ISSUE TITLE
REUSE linting in pull request: only check files that are changed or created

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#332]
The REUSE linter will probably always fail, because there will always be some files without an (SPDX) license. To overcome an always failing pipeline, we suggest to check only those files that are changed in a PR.

**Comment by ewan-escience** [comment]
Since [this issue](https://github.com/fsfe/reuse-action/issues/13) on the reuse-action repo indicates that it will probably never be possible to only check changed files, we concluded that the REUSE action is not suitable for our workflow.
