### ISSUE TITLE
Organisation mantainer cannot create research units

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#343]
The organisation maintainer is not able to create organisation units. After saving the following error is shown.

![image](https://user-images.githubusercontent.com/9204081/174588152-3ec4f323-8f53-4cf8-8604-0dae263859df.png)

The error is related to RLS, and changes we made recently not to allow assigning of primary_maintainer to this unit. Is this approach correct? If yes, assigning primary_maintainer should be removed from the process, but it rises the question who should be able to edit this researh unit? If not, the RLS should be updated to support assigning primary maintainer from FE for child organisations only.

## Points to discuss

**It is important to note that research unit is simply an organisation that has a parent organisation.**

Concerning this feature there are following points to discuss and implement accordingly:
- Who is able to add new Research units? Only primary maintainer or any organisation maintainer
- Who will become primary maintainer of new research unit and who can become "ordinary maintainer" of it (the maintainer invite feature is available to research units (sub organisations)? 
- Who is able to edit research unit? primary_maintainer of parent organisation or any maintainer of parent, BESIDE the research unit primary_maintainer and ordinary maintainers. Note! there is "moving" hierarchy tree organisation -> research unit(s)
- Who is able to delete research unit? At the moment there is no delete functionality.

**Comment by dmijatovic** [comment]
@jmaassen @ctwhome @ewan-escience @cmeessen @ruester I had a quick look at this bug. It rises a number of points we need to discuss and implement accordingly.

**Comment by ctwhome** [comment]
Probably not relevant at this point but i would like to discuss aldo the name of research units, I'm not sure if it is inmediatelly recognizable. Maybe "group" cloud be a wider term including other 'group' concepts?

A group could have the type of: Department, section, independent group... etc.
