### ISSUE TITLE
Improve or change the 'Update information' label inside the software pages

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#348]
The cards are showing when the software was updated wrongly. It is probably taking when the data scrapers did run. 

Maybe we can discuss if that information is needed in the card itself, we could move it to the software page itself, and remove it from the card

![](https://user-images.githubusercontent.com/4195550/174998173-9f712677-0397-4d71-9a09-45161b9d8a83.png)

**Comment by ewan-escience** [comment]
The scrapers were improved so they don't update this field anymore. So we only have to discuss if this info should stay on the cards. @jmaassen, what do you think? 

If we conclude that this info can stay, we can close this issue.
