### ISSUE TITLE
Add "more" menu to the cards in the user section

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#349]
The user section shows my software, my projects and my organisations.

We should add "more" button to the cards in this section similar to ones we added in the organisation section. The menu options should be different,  I think on: Edit, View and maybe Delete(?).

## Example organisation section

![image](https://user-images.githubusercontent.com/9204081/175118910-533c13b4-7fd3-475d-b0df-91ddc1e5088e.png)

## Current user software section

![image](https://user-images.githubusercontent.com/9204081/175119579-9b29b58e-2c6a-49de-870c-5b958ca456c4.png)

**Comment by jmaassen** [comment]
Close for now
