### ISSUE TITLE
Show all items of child organisation at the parent level too

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#357]
### Parent organisation should include all software and project items from the children (research units)

Currently organisations and research units (child organisations) keep their own software and projects. The software and project counts are performed in similar way. Currently if a child organisations references different software from the parent, these are not shown and not counted at the parent level.

I expect that showing all software and projects owned by children organisation would be more natural approach. My assumption is that user expect this behavior. The counts of software and project should be unique, in other words one software reference by multiple child organisation should be count once.

**Comment by dmijatovic** [comment]
@jmaassen, @ewan-escience, @ruester, @cmeessen Are you agree with this approach?

**Comment by cmeessen** [comment]
I agree, makes sense.
