### ISSUE TITLE
Theme provider

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#359]
Ability to support different themes, for eScienceCenter but also the rest of the organizations (Helmholtz).

Tasks: 
- [x] Unify theming between Tailwindcss and MUI
- [ ] Be able to switch dynamically in runtime between dark and light theme
- [ ] Document how to build themes
- [ ] Remove doubled themes from MUI

**Comment by jmaassen** [comment]
See Draft PR #410
