### ISSUE TITLE
Tagging the license into the documentation markdownfiles breaks frontmatter variables

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#373]
The documentation site uses YAML frontmatter variables inside the markdown files to specify properties of the theme. 

Anything that goes before the `---` characters will break the frontmatter format. 
The license script adds content before the YAML code breaking the documentation template. 

We should find a way to exclude all markdown files inside the path:  `/documentation/docs/*.md`

Markdown frontmatter example: 
```md
---
foo: var 
---
# Markdddown file title
....
```

**Comment by cmeessen** [comment]
I see several solutions here.

### 1) use `.license` filese

The easiest would be to add a `.license` file to every file that requires a yml header at the top. Then we could continue using the reuse-tool together with the pre-commit hook, and copyrights will be added as needed. However, if many Markdown files require this header, there will be plenty of `.license` files cluttering the directory which may be a bit odd.

### 2) use `dep5`

Another solution would be to add a `.reuse/dep5` file. We can use wildcards here to define licenses for file types, e.g. for now

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: RSD-as-a-service
Upstream-Contact: The RSD Developer team <rsd@esciencecenter.nl>
Source: https://git.example.com/jane/my-project

Files: documentation/docs/*.md
Copyright: 2022 Netherlands eScience Center
           2022 Jesús García Gonzalez (Netherlands eScience Center) <j.g.gonzalez@esciencecenter.nl>
License: CC-BY-4.0
```

However, the reuse-tool does not work with `dep5` at the moment, and we would have to write a more elaborate pre-commit hook here. I guess that pre-commit hook would deserve it's own repository in that case :) A workaround may be to state the copyright to the "RSD Developers Team", but I think in that case (if we are strict), we need Contributor License Agreements for every external contributor.

OR

### 3) Ignore the documentation in the pre-commit hook

We add a check in the pre-commit hook that will ignore all Markdown files in the `documentation/docs` directory. But then we would let go of the REUSE principles.

I would favour either 1, or if that solution is not satisfactory, number 2. What does everyone else think? @jmaassen @dmijatovic @ewan-escience

**Comment by ctwhome** [comment]
Thanks for the detailed description. 

My preference would be the third one: excluding the documentation site. The doc site itself keeps track already of the contributors for a particular document and shows it in the footer.

Option 1 is could be more cumbersome since there is a need to create a .license file for each documentation page. It works, but it also adds complexity. it is something to be remembered in the future and that always adds complexity. 

Option 2 is also fine.

**Comment by jmaassen** [comment]
This was solved

**Comment by cmeessen** [comment]
@jmaassen: @ctwhome did a hotfix and copy-pasted the `README.md` to `README.license.md` (strange that it works, because I think the file should be named `README.md.license`). This file does not contain valid license information as of now, so I would like suggest to re-open and decide for option 1 or 2. The fastest would be to enter the correct license info into the `.license` file.

**Comment by jmaassen** [comment]
Sure, let's reopen.
