### ISSUE TITLE
Search for software and projects needs sorting/filtering

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#385]
When searching for either software or projects, we need more than only a single text entry box.
Also, what exactly is being searched? It seems like project or software title + description? But not the rest of the meta data?

It would be useful to be able to sort and filter on at least:

For projects:
* running / finished (might not be needed if 'finished' is sorted to the end)
* domain

For software:
* expertise / technology used
* programming language?

Both:
* organizations
* contributors

After discussion with Dusan:
Add a 'Research Domain Page', accessible via a url. $RSD/researchdomain/TAG
where TAG is sort-of drill down;
* PE, would cover all PE1, PE1_1 etc
* PE1 would cover only PE1 and PE1_*
* etc.
note that if project have fi. the PE1_1 label, they need not have PE.

**Comment by jmaassen** [comment]
At the moment we only search the title + text. We could add searching in tags and maybe add some special search command to restrict search to a certain field? Like "tag: topic"

**Comment by jmaassen** [comment]
We'll think about this a bit more for a later release

**Comment by jmaassen** [comment]
Feedback from Helmholtz: should the markdown also be searched?

**Comment by jmaassen** [comment]
Maybe an "advance search page" would be useful?

**Comment by Normo** [comment]
> Feedback from Helmholtz: should the markdown also be searched?

@jmaassen That would be really helpful for us :pray:

**Comment by ctwhome** [comment]
> > Feedback from Helmholtz: should the markdown also be searched?
> 
> @jmaassen That would be really helpful for us 🙏

Searching markdown would be possible but we are not storing the markdown files that come from an URL, only those descriptions that have been manually written. 
![image](https://user-images.githubusercontent.com/4195550/190343764-331fd373-8049-4a8c-8386-7e7479c44649.png)


I guess we could save a version of the markdown files in our database as a backup and be able to search within our system. It might get outdated really soon so we should run a cron job (weekly, monthly?) that revisits the markdown linked and updates our database.  

It would probably improve the findability and user experience of the search much more.
