### ISSUE TITLE
More next / previous page buttons when searching software

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#386]
The list of software, projects, and organizations can be quite long.
Currently, pagination is used to make the list more manageable.

Issue: when I've scrolled to the bottom of a page, i would expect a button to go to the next/previous page (or the next/previous buttons at the top of the page to stay visible, like fi. Excel's freeze cells option).

**Comment by dmijatovic** [comment]
@jiskattema Thanks for point this out.
