### ISSUE TITLE
URL change: will research-software.nl redirect to the new RSD?

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#388]
We've been using the old RSD at research-software.nl in many call texts and other advertising.
Will the old URL stay available, possibly as a redirect to the new site?

**Comment by jmaassen** [comment]
Yes, our plan is to redirect the old links to the new RSD implementation. To do so, we must first shut down the old RSD which we will do early september.

**Comment by jmaassen** [comment]
After a successful test run, we'll shut down the old RSD and implement the redirect.

**Comment by ewan-escience** [comment]
This is done now, see e.g. https://www.research-software.nl/ and https://research-software.nl/software/xenon.
