### ISSUE TITLE
eScience accounts not a member of NLeSC

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#390]
When logging in using my @esciencecenter.nl credentials, I'm not a member of the Netherlands eScience Center organization.
I cannot edit existing projects and software.

**Comment by ewan-escience** [comment]
In the current setup, you can become a maintainer (i.e. get editing rights) of individual software packages and projects. We plan to send out maintainer invitations to all the contact persons of software packages and projects. In the meanwhile, you can contact us privately to indicate of which software packages and projects you want to become a maintainer.

**Comment by jiskattema** [comment]
I would like access to all NLeSC projects and software; i think the other project managers too ;)

**Comment by ewan-escience** [comment]
I just did this for Niels and you. A hard refresh might be needed. For the other program managers, they need to login first (so we know their account id).

You can now also invite other maintainers.

**Comment by jiskattema** [comment]
Thanks! i can now edit projects and software for NLeSC.
I'm still not a member of the 'eScience Center' organization (on my profile page, organizations is empty)

**Comment by ewan-escience** [comment]
There is no such concept of being a member of an organisation. You can only be a maintainer of an organisation.

Contributors or team members of software or projects respectively can have as affiliation an organisation, but these are free text fields and not linked to the organisations in the database.

**Comment by bakhshir** [comment]
Following on this: my account id is 8a49e0b7-e0a9-4616-9513-6e94e82c45df

**Comment by ewan-escience** [comment]
@bakhshir I just made you a maintainer of all software and projects. Still waiting for Pablo to login.

**Comment by ewan-escience** [comment]
Done for Pablo as well. In the future, the person to create a software or project page can invite other maintainers. When something goes wrong, you can of course email us. I'm closing this issue now.
