### ISSUE TITLE
user/profile page does not list ORCID or other identifiers

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#391]
On the user profile page (the one here: https://research-software-directory.org/user/profile ), i would expect a way to add/view some more metadata. I'm thinking of:
* orcid
* google scholar id
* github id?
* research gate id?

**Comment by jmaassen** [comment]
At the moment there is no public profile page, but there are some request to add those. If we do it would make sense to add additional information, although this also has GDPR implications.

**Comment by maaikedj** [comment]
Related to this, the Account ID code that is now shown at the profile info seems meaningless to the user, can we remove it? Or does the user need it for something?

**Comment by jiskattema** [comment]
@jmaassen we already list persons with name, email, and ORCID at fi. the software pages. Any (likely) GDPR issues need to be solved anyways. Even if we don't show it, it is in the database and some parts of the GDPR will apply

**Comment by jmaassen** [comment]
For now we decided not to collect and show this data yet. We may reopen later.
