### ISSUE TITLE
Missing pages: About, Privacy Policy, ToS

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#393]
The pages mentioned in the title are missing.
Especially the Privacy Policy and Terms of Service are urgent, as the website is already life.

**Comment by jmaassen** [comment]
Correct, we have a draft for both (created by a lawyer) which we will add later this week.

**Comment by jmaassen** [comment]
They are now online. We do plan to add more info about cookies and have a final check with an IT Legal person.
