### ISSUE TITLE
import from old RSD: ORCID missing

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#394]
For the AA-ALERT project i'm listed as contributer, but my ORCID is missing. As the old RSD doesnt allow me to access the admin interface at the moment, i'm not sure if this is an import bug, or just missing data.

**Comment by jmaassen** [comment]
The old RSD did not support ORCID's, so these are missing from all data we migrated from there. 

I'll send you a link allowing you to manage the content of the AA-Alert project later today or tomorrow. This will allow you to add you orcid.

**Comment by jiskattema** [comment]
I'm already admin for that project; the issue is then that the data in the new RSD is incomplete.
TODO: add ORCIDs to all NLeSC employees

**Comment by jmaassen** [comment]
Indeed, the data imported from the old RSD is as complete or incomplete as it was before. It would be good if all NLeSC employees had their ORCID in the RSD, but I'm not even sure if all of them have an ORCID. Is this part of the onboarding?

**Comment by jiskattema** [comment]
We should put this to the section heads i think; collect ORCID for all RSEs.
@jmaassen can you send a mail about this to the SHs?
