### ISSUE TITLE
Team section on project website needs ordering

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#399]
The research team on the project website needs an ordering:
Seef fi. https://research-software-directory.org/projects/aa-alert

Suggested ordering:
* The Principle Investigator (or, for this older project, the Lead Applicant) needs to be listed first. Maybe starred or something? (like contact person)
* Co-applicants next
* RSEs next
* TL
* PM

**Comment by jiskattema** [comment]
suggestion for implementation: add a priority field to the team members; ordering is then by increasing (decreasing) priority. Within the same priority level, sort alfabetically.

Mr X - prio1
Mrs Y - prio2
RSE-A - prio3
RSE-B - prio3
RSE-C - prio3
TL - prio4
PM - prio5

Or (easier?), make the set of team members ordered (ie a list), and render in specified order.

**Comment by jmaassen** [comment]
We could use the same approach as testimonials, where you can determine your own order.

**Comment by jmaassen** [comment]
This would require a good library for this (and add positions in the database).

**Comment by jmaassen** [comment]
Related to issue #463
