### ISSUE TITLE
Label 'view' when editing software/project confusing

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#404]
When editing existing software or a project, on the top right of the page there are 2 buttons 'View' and 'Save'.
1. It is clear what 'Save' does; but 'View' would be better called 'Close' ?
2. there are no popups providing more information. fi. "Save changes to project" and "Discard changes to project"

**Comment by jmaassen** [comment]
We are working on auto save at the moment, so the "save" button will go away. We can rename the "view" button to "view page".
