### ISSUE TITLE
First visitor flow improvements

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#408]
As a first time visitor, i feel a bit lost on the website.

The fancy landing page with jumbotron forces me to click on the white 'Discover software' button, that stands out against the black background. However, i then end up on the minimalistic search page (see also  #385 ).
There i see ~10 pieces of software i know nothing about.
Maybe a guided tour, or some explanations, or more obvious search functionality could help?

Once you're familiar with the RSD, i think the minimalistic look is a good thing.

**Comment by ctwhome** [comment]
We are busy with the final touches on the design. The software page will change when we add the filters more visible, so the feeling is that you don't end up on a simple page with blocks, but actually a place to 'find/discover' software. 

Thank you for the feedback. Let me close the issue for now but keep an eye on the new design we are currently working on.
