### ISSUE TITLE
Improve Markdown editor with a simple WYSIWYG menu bar

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#409]
probably using this small library would improve the edition of the Markdown description inside software and project pages

https://simplemde.com/
![image](https://user-images.githubusercontent.com/4195550/178912264-371ccce3-7938-4cd2-bd39-b7ae426c5e1f.png)

**Comment by jmaassen** [comment]
I received some feedback from David Moonen (MEMIC) regarding this: 

Overall, adding information was very intuitive for him. He didn't know markdown, however, so it took him some time to find the syntax online. The icon bar, or a link to some info on markdown would have helped in this case.

**Comment by ewan-escience** [comment]
[SimpleMDE](https://github.com/sparksuite/simplemde-markdown-editor) was last updated 8 years ago and is [abandoned](https://github.com/sparksuite/simplemde-markdown-editor/issues/829). A clone of it is [EasyMDE](https://github.com/Ionaru/easy-markdown-editor) (see also [NPM](https://www.npmjs.com/package/easymde)), which is maintained more actively, but is a one-person project. There is also [ink-mde](https://github.com/davidmyersdev/ink-mde) ([NPM](https://github.com/davidmyersdev/ink-mde)), but it is also a one-person project and is even less popular.

Strangely enough, there doesn't seem to exist any popular, mature, well-maintained, embeddable Markdown editor, so we might just have to abandon this idea.

**Comment by dmijatovic** [comment]
In addition, we currently use the following markdown tools that should be upgraded:
- react-markdown: v8.0.7 to be upgraded to v9.0.1
- remark-breaks: v3.0.2 to be upgraded to v4.0.0
- remark-gfm: v3.0.1 to be upgraded to v4.0.0

We also need to investigate if the editor can be also used as viewer only because we use mentioned makrdown tools for both editing and displaying markdown content.

**Comment by dmijatovic** [comment]
This week in the JS newsletter I received there is "promotion" of new markdown framework [@milkdown](https://milkdown.dev/docs/guide/getting-started). I think it worth checking thisone too.

**Comment by ewan-escience** [comment]
Maybe we will do this for the KIN project.
