### ISSUE TITLE
Handling situation when commit graph cannot be displayed

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#419]
There are some circumstances, where the commit graph cannot be displayed:

* there is no repository
* the given repository URL is a group (could be handled otherwise)
* the repository is private
* the repository provider is currently not supported

If a "Get started" URL is given, there is currently a lot of empty space:

![image](https://user-images.githubusercontent.com/14222414/179946049-37a9a508-73bb-4cf4-b737-22b1ee5c691a.png)

If the graph cannot be displayed, there could be a heartbeat line indicating that there is something missing, and that this is not a bug, e.g. like this:

![image](https://user-images.githubusercontent.com/14222414/179946349-c9dc4db3-f928-4092-8d1e-b9776fec8176.png)

By displaying this graph as a replacement, we might nudge the maintainers towards making their software available. The text message should be customisable so we can adjust it to the actual situation (see list above).

**Comment by dmijatovic** [comment]
@cmeessen Nice addition! I have two requirements for this graph:

1. Component should accept `message` property, which can have a default value as in the picture
2. The color of the graph line should be variable and use primary color from the theme

**Comment by jmaassen** [comment]
This looks very nice indeed. I would be in favor of showing a graph like this when there is no data available. 

Maybe a similar solution can also be used in other places. For example, the presence / content of the citation block depends on the availability of a conceptDOI, and the presence of a CFF file. Currently, the citation block is either missing, partly filled, or fully filled, but it's not always clear why.
