### ISSUE TITLE
Edit project - team members (feedback Rena)

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#433]
# Adding team members

1. It does not offer to add new person when there is a match in ORCID but it is not same person
2. It does not support search by ORCID. Sometimes search returns lot of persons with the same name. It is easier to provide ORCID instead of name.

## Example Jan Jansen
![image](https://user-images.githubusercontent.com/9204081/180656756-9a6bf919-26cd-49df-8d06-19e507dd3877.png)

## Note
The similar feature should be provided in contributors section of edit software page.

**Comment by jiskattema** [comment]
copy-pasting a valid orcid in the 'find or add team member' would make data entry much easier.
