### ISSUE TITLE
Add support for Matomo

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#435]
For webstatistics, we are using a self hosted instance of [matomo](https://matomo.org/). We suggest to implement a feature equivalent to the hotjar integration. If a matomo ID is given in the `.env`, the matomo integration should be activated.

**Comment by dmijatovic** [comment]
@cmeessen I would like to hear more about how you are using it and what it offers. We might move from hotjar to matomo too. We use hotjar on dev server only (not in the production). It would be nice if you can present matomo to us in September when we are all back from vacation.

cc: @jmaassen @ctwhome @ewan-escience @maaikedj
