### ISSUE TITLE
cannot change project image

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#437]
Once the project image is uploaded, it cannot be replaced with another image. The project page just "caches" the first image, and overwrites the newly uploaded image with the former. If one deletes the project image, saves the page - the project image is not shown anymore. But one uploads a new image, the "cached" first uploaded image shows up again.

I tried with several pages including 

https://research-software-directory.org/projects/rs-dat and 
https://research-software-directory.org/projects/smartnets

**Comment by bakhshir** [comment]
update: it is really an issue with cache. The second page now has an updated image. 
From the user perspective though, there needs to be warning that it might take time until cached version is renewed.

**Comment by jiskattema** [comment]
i had the same issue: replacing a project image with an old image didn't seem to work, and the odl one kept reappearing.
What worked:
1. remove project image
2. save
3. add new image
4. save
5. Clear browser cache (or in my case, disable caching using Firefox dev tools)
6. reload

**Comment by jmaassen** [comment]
See #440 for discussion on this topic

**Comment by ruester** [comment]
I could be solved by adding another parameter to the URL which is saved within the DB and updated if a new image was uploaded, like so:

`/image/rpc/get_project_image?id=c9407e1b-789f-4eec-b25a-5950b28dcbf0&key=1234`

Querying this URL again should use the cache of the browser.
After saving a new image to a project the key is changed in the DB, which results in a new URL and the browser should not use the cache in this case:

`/image/rpc/get_project_image?id=c9407e1b-789f-4eec-b25a-5950b28dcbf0&key=9876`

**Comment by jiskattema** [comment]
> An alternative would be, for the uploader of the image, to fetch the image with a Cache-Control no-store header after uploading, as described [here](https://alphahydrae.com/2021/02/how-to-display-an-image-protected-by-header-based-authentication/). This would not drop the cache for other visitors though.

When does the cache expire for other visitors?
For me, even 24 hours with the 'old' image for visitors would not be problem.

**Comment by ewan-escience** [comment]
72 hours

**Comment by jiskattema** [comment]
ha! that's just on the limit between too long and ok.

In practice, the image hardly ever changes. The only issue is when changing it in the admin interface, you need feedback if it worked and on how it looks. Especially when you have to zoom and/or crop the image. 
Additionally having a notification or info bubble warning on the change-image page that it can take up to 72 hours for repeat visitors to see the new image could be sufficient.

**Comment by ruester** [comment]
> That would mean you cannot link to that image anymore, as you would need to know the (changing) key.

No that key would just be for the browser to fetch the image again (like a random value). The underlying stored image would always be the right one, so you still get the correct image with `get_project_image` (but this may be cached then in the browser).

**Comment by ewan-escience** [comment]
> by adding another parameter to the URL which is saved within the DB and updated if a new image was uploaded

I thought you meant with this that extra parameter had to be saved in the database. 

If we use the browser only parameter, then the next time the uploader views the public project page, this parameter is not provided, so doesn't the browser use the old cache again?
