### ISSUE TITLE
Pages administration: allow links to external pages

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#438]
For convenience, we will not host the data protection declaration by ourselves, but will instead link to the declaration of the hosting institution (i.e. GFZ). It would be great if, instead of a complete markdown page, we could use the new administration frontend to add such links.

**Comment by bakhshir** [comment]
In the project pages, one can add project links with description and a link.

![image](https://user-images.githubusercontent.com/16703268/180826735-3f1b3c2a-7043-48f5-bd0a-dc9d7f6d82a1.png)

**Comment by cmeessen** [comment]
Thank you very much for the hint @bakhshir. I was referring to the data protection declaration in the footer of the page that were implemented with #415. Apologies that I was unprecise here. They are accessible via "Administration", if the user is an RSD Admin:

![image](https://user-images.githubusercontent.com/14222414/180850245-1b91e6ab-3dd6-4235-a826-5abd573ea3bd.png)

**Comment by jmaassen** [comment]
This should propably be part of #410 ?
