### ISSUE TITLE
export functionality for (project) output

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#445]
It would be very handy to have a functionality to export project output to one of the used formats like xml, json, or even html. As an example I attaching Zotero report which is something that LAs sometimes ask [Zotero Report.zip](https://github.com/research-software-directory/RSD-as-a-service/files/9188939/Zotero.Report.zip)

**Comment by ewan-escience** [comment]
The RSD has an [API](https://research-software-directory.org/api/v1/) available. We use PostgREST, you can find the documentation [here](https://postgrest.org/en/v9.0/api.html) and a schematic overview of the tables we use [here](https://research-software-directory.github.io/RSD-as-a-service/api.html). 

Say for example you want the output of the [PROCESS](https://research-software-directory.org/projects/process-2) project. You can get the JSON data [here](https://research-software-directory.org/api/v1/project?slug=eq.process-2&select=*,mention!output_for_project(*)). Would that be sufficient?

**Comment by bakhshir** [comment]
It looks good so far. Jisk is also looking into the API. I will close the issue for now, and reopen if we have any issues/requests.
