### ISSUE TITLE
Delete software or projects

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#448]
Is there a way to delete software of projects? i cannot find it on the edit page.

**Comment by dmijatovic** [comment]
@jiskattema No, at this moment there is no option to delete software, project or organisation. But if there is a need we can implement this feature in the future.

**Comment by jmaassen** [comment]
Deleting entries may be difficult if many other entries link to it. We probably need to use the same solution as Zenodo: deleting can only be done by asking the admins?

**Comment by ctwhome** [comment]
I would also expect to be able to delete a test software or project. We could give some important warnings before being able to delete a project or organization. Like it's done in different applications: i.e.
![image](https://user-images.githubusercontent.com/4195550/191335312-26607450-3402-4ee3-9ef8-333b5c0e3669.png)

**Comment by ewan-escience** [comment]
Implemented by #1286.
