### ISSUE TITLE
Use controlled vocabulary for software contributor roles

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#450]
We have received a [suggestion](https://github.com/hifis-net/RSD-as-a-service/issues/24) that it would be useful to use a controlled vocabulary for the contributor roles. The following options were mentioned:

* [DataCite Contributor Role](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#7a-contributortype)
* [ISO19115 CI_RoleCode](https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml)

**Comment by jiskattema** [comment]
Of the two suggestions, the ISO19115 seems best; but still doesn't match NLeSC roles exactly.
Just for reference, we would have:
* Principal investigator / lead applicant /..
* co-applicant
* collaborator / our engineers
* project manager from our/funder side
* contact point

**Comment by jmaassen** [comment]
At the moment we have a free text field for roles because its hard to select a list that suits everyone. Maybe we could do something similar to keywords, where we have a free text field with auto-complete suggestions? These suggestions could then be pre-filled with one of the standards suggested?
