### ISSUE TITLE
Project image not suitable for logos

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#452]
The project images are displayed as background images of an element with the properties

```css
background-position: center top;
background-size: cover;
```

Whilst this is very good for displaying picutres, it makes project logos unreadable. Here is an example for the HIFIS logo:

![image](https://user-images.githubusercontent.com/14222414/181232980-46924574-b377-47d9-88fe-afe7b42d5731.png)

![image](https://user-images.githubusercontent.com/14222414/181233014-99c2d68f-6611-4fe6-a752-c7e5d1712be7.png)

A possible solution would be to allow the user to influence the `background-position` and `background-size` properties.

**Comment by bakhshir** [comment]
This is related to my issue #443
