### ISSUE TITLE
Research Domains / ERC classification is displayed as codes only

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#453]
We received [feedback]() about the ERC classification display:

> The ERC classification is displayed strage in the Detail view: I shows some rather meaningless classification code ("PE", "PE10") and just on mouse over you can access the classification name/description. It would be better to show it als "Physical Science and Engineering" like in the entry form.

Here is an example screenshot:

![image](https://user-images.githubusercontent.com/14222414/181233793-09b30b84-4b4d-4633-afb2-264ef7724d77.png)

**Comment by jiskattema** [comment]
I dont mind short codes, some of the ERC descriptions can be quite long.
I agree the current situation is not very clear though; see also #447

**Comment by ewan-escience** [comment]
We'll keep the short codes. Those buttons should become a link to a search page where you see all projects with that research domain. On that page, the full text should be visible. 

Also note that when you hover on the label, you also see the full text. We should indicate (maybe with an icon) that hovering indeed works.
