### ISSUE TITLE
Users may have difficulties to find their hidden projects

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#455]
Here is a suggestion that we received in some [feedback](https://github.com/hifis-net/RSD-as-a-service/issues/24):

> when I went away from the unpublished Project, to link it to a published software, it was kind of unintuitive to find the way back to the unpublished project. I didn't expect it to be under my profile picture, just found it by searching for it. I would have expected to find it flagged as unplublished when pressing "projects" at the top ribbon.

**Comment by dmijatovic** [comment]
We can add additional text under the Publish section like "Unpublished software can be found under your profile"

![image](https://user-images.githubusercontent.com/9204081/197515832-2dbf993e-a692-45ec-8e78-6ae8126cffd6.png)
