### ISSUE TITLE
Return to Organisation's/Projects and not Organisation's/Software

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#462]
From #459:

When navigating Organisations -> \<Some organisation\> -> Projects -> \<Some Project\>, and then using the "Back" functionality of your browser, you end up on the "Software" page of the Organisation instead of the Projects page

**Comment by jmaassen** [comment]
@dmijatovic Is this easy to fix?

**Comment by dmijatovic** [comment]
These are dynamic routes with variable depth. We could solve it by using query parameter. I need to further investigate the impact. I'll come back to this probably in the next milestone.
