### ISSUE TITLE
project pages: case sensitivity of entered DOIs

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#464]
if I enter output with DOI in capitalized letters (e.g., 10.4230/DagMan.6.1.1), RSD does not see the existing entry and tries to add it from another source (e.g., DataCite). This leads to an error as shown in the screenshot
![Screenshot from 2022-07-29 13-54-48](https://user-images.githubusercontent.com/16703268/181756571-a25681c8-a0e9-442b-8228-10bfa7cd7955.png)

If I enter a title or its DOI in lowercase letters (in the same example, 10.4230/dagman.6.1.1), the existing RSD entry is found.

This could potentially be problematic to users, because i just copy pasted DOI the way it was written in the article.

**Comment by ewan-escience** [comment]
DOI's are indeed [case insensitive](https://www.doi.org/doi_handbook/2_Numbering.html#2.4). We'll look into this.
