### ISSUE TITLE
Create and maintain DB diagram

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#47]
We need to keep up to date a diagram for the database, It is probably something cumbersome at the beginning but it will help in the short and long term. 
Example: 
![image](https://user-images.githubusercontent.com/4195550/145171190-13328134-39bd-4163-afcd-a1faad97af54.png)

### Look at
- See if there are automatic diagrams, or maintain one manually
-  https://www.holistics.io/blog/top-5-free-database-diagram-design-tools/

**Comment by ewan-escience** [comment]
An easy solution is to create and export this from DBeaver.
