### ISSUE TITLE
Specify log retention period

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#470]
Currently, the nginx container has no specification as to how long log files are stored. As far as I could see, some default values from the docker image are used (the following output is from inside the nginx container):

```
$ cat /etc/logrotate.d/nginx 

/var/log/nginx/*.log {
        daily
        missingok
        rotate 52
        compress
        delaycompress
        notifempty
        create 640 nginx adm
        sharedscripts
        postrotate
                if [ -f /var/run/nginx.pid ]; then
                        kill -USR1 `cat /var/run/nginx.pid`
                fi
        endscript
}
```

This corresponds to 52 days at the moment. According to the data protection declaration of the GFZ, we need to remove the logs after 7 days. So it would be very handy if we added an option to adjust the `logrotate` settings here.

/update:

Sorry, my mistake, I did not look more closely. The logs are piped from `/var/log/nginx/access.log` to `/dev/stdout` (or `error.log` to `/dev/stderr`), so they end up in the docker logs. In `docker-compose.yml`, we can [define](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging) the maximum amount of space to store, and the number of files to store.

**Comment by Normo** [comment]
> Sorry, my mistake, I did not look more closely. The logs are piped from `/var/log/nginx/access.log` to `/dev/stdout` (or `error.log` to `/dev/stderr`), so they end up in the docker logs. In `docker-compose.yml`, we can [define](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging) the maximum amount of space to store, and the number of files to store.

@cmeessen  If I understand [this](https://docs.docker.com/config/containers/logging/json-file/#options) correctly, `max-file` refers to the file size and not days. This means that the log will be only rotated when the `max-size` is reached.

**Comment by Normo** [comment]
I see three options here;
1. Install and start `logrotate` inside the `nginx` image.
2. Use a docker volume for `nginx` logs and make it available to an additional `logrotate` container.
3. Use a docker volume for `nginx` logs and make it available to the host, where `logrotate` is running.

**Comment by cmeessen** [comment]
If we want to manage logs from all containers, a separate `logrotate` container might be useful. @Normo what would you prefer and why?

**Comment by ruester** [comment]
> I prefer a separate `logrotate` container to follow the "one container, one process" principle.

Sounds to me like more overhead in getting the logs from the nginx container to another container? The nginx container would "communicate" via a mount point, I guess? So that a logrotate process handles the files in that mount?
Since the logs are generated in the nginx container I would suggest to add logrotate to the nginx container and do the rotating there, which would be much simpler to maintain/debug in the long run...

**Comment by cmeessen** [comment]
The idea is to handle logs from the scrapers (and potentially other containers). Couldn't we use a `log` volume that is mounted in all containers and let the content be handled by the `lograte` container? @Normo

**Comment by ewan-escience** [comment]
This is not the responsibility of the RSD software, moved to management.
