### ISSUE TITLE
Menu disappears for smaller screen widths

### ISSUE THREAD

**Issue by Peter9192** [research-software-directory/RSD-as-a-service#471]
I noticed that the menu on the landing page disappears when I reduce the width of my browser window:

With menu:

![image](https://user-images.githubusercontent.com/17080502/182429194-98d39314-6876-4c5f-8fc0-873cdc06dda2.png)

Slightly smaller window:

![image](https://user-images.githubusercontent.com/17080502/182429040-a3b9f54c-68e2-442a-b557-6843ea412575.png)

**Comment by ewan-escience** [comment]
Good catch. We used to have a hamburger like menu that would replace those menu links when the width is below some threshold, but some recent update must have broken this. I'm pinging @dmijatovic and @ctwhome. They can fix this but are unfortunately on holidays.

**Comment by ewan-escience** [comment]
Note that you can click on the search bar (`Search or jump to...`) to get a list of the menu items.

**Comment by dmijatovic** [comment]
We should further investigate the possibilities and improve layout. Currently the menu is hidden for tablets in the portrait mode because there is no sufficient space for all "features" when user is logged in and access the search box that expands on focus. Because search also supports jump to available pages from the menu options I decided to hide menu. See image.

![image](https://user-images.githubusercontent.com/9204081/186891321-8996bb10-eb9c-4cdc-9576-c42364435ccb.png)

**Comment by Peter9192** [comment]
Perhaps adding a menu icon (hamburger or downarrow?) *inside* the search bar, on the far right, could be a subtle hint?

**Comment by ctwhome** [comment]
for some reason, the dropdown menu with the pages disappeared. Did we hide it on purpose?

**Comment by dmijatovic** [comment]
@cwthome Yes, I disabled it because we had no sufficient space for all buttons on mobile. So we should make further improvements taking into a count all possible options and different formats. This was quick fix based on problems reported on mobile.

**Comment by ctwhome** [comment]
is it possible to add the extra functionalities to the current dropdown menu?

![](https://user-images.githubusercontent.com/4195550/186904950-cf25e248-6721-4edc-85dc-3918ae3b9f92.gif)

**Comment by ctwhome** [comment]
This is the space left after login and with the plus button

![](https://user-images.githubusercontent.com/4195550/186905603-90b2a7cb-d49e-4787-b48a-a60bf339be1c.png)

Is there any other menu to be displayed?

**Comment by dmijatovic** [comment]
@ctwhome It would be great if you can improve it! The problem was on mobile screen with ca. 375px width.

**Comment by ctwhome** [comment]
I believe 375 are iphones 7 and 8. i will take a look at it, thanks

**Comment by ctwhome** [comment]
at 375px it works. I can see a problem with the old iPhone 5 at 320px, but these are really old phones, but even with that the menu still works.

Galaxy fold outer screen is also a problem, it kind of breaks many things:
![image](https://user-images.githubusercontent.com/4195550/186908594-6ee67cc3-468d-4f5a-9c6c-742b3af9af01.png)


We can reduce the margins at that point, the question is if we should support devices older than 9-10 years or with such a small vertical space?

iPhone 5 and 5s (2012, 2013) width: 230  iPhone 5s 2013)
iPhone 6 width: 375. 

![image](https://user-images.githubusercontent.com/4195550/186907257-19c4b247-c1a6-4921-bc3e-3d70614e0b34.png)

**Comment by ctwhome** [comment]
My preference would be to enable the dropdown menu for now and open a UI fix for those edge cases rather than disabling mobile and tablet it for together.

**Comment by dmijatovic** [comment]
@cwthome Note that you can navigate using jump to options from search box, which is not that obvious. I agree, I think we could hide pages menu for very small screens <375px and show it between 375 - 1024. Maybe we could setup a minimum width of app to 375px?

**Comment by ctwhome** [comment]
That could be also a solution indeed, jumping the logo to a new row with flex wrap 😁
