### ISSUE TITLE
Text of public pages disappears occasionally

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#475]
While editing the public pages of the terms of service and privacy policy, I've noticed twice that unsaved text disappeared when focus changed to another tab of my browser. I'm not entirely sure what triggers it, and I can't seem to reproduce it in a test case.

**Comment by ewan-escience** [comment]
This happens when the cookie with the authentication token refreshes (after about 55 minutes), which causes the page to re-render.
