### ISSUE TITLE
Fix favicon

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#478]
At the moment the favicon of the RSD is the old esciece center one. We should update to the new one, or (even better), use an RSD logo instead.

**Comment by ctwhome** [comment]
I am thinking that it might be a better approach to indeed remove the old eScience logo from the favicon and replace it by the placeholder we have now until we have a final logo. what do you think @jmaassen?

<img width="823" alt="image" src="https://user-images.githubusercontent.com/4195550/186115316-0a353c90-40e6-48ec-ae6f-abf1e8bbc902.png">

**Comment by jmaassen** [comment]
Sure, that would fine for now.
