### ISSUE TITLE
RSD WordPress plugin

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#483]
The comms department at NLeSC would really like to include data on projects from the RSD onto the corporate site. The simplest way to do so would be to use a wordpress plugin like json-content-importer (https://json-content-importer.com) and talks to a rest API on the RSD.

Maybe we can experiment a bit with this to see is this is feasible and afterward discuss this further with comms.

**Comment by bakhshir** [comment]
fyi: It is related to my issue #445

**Comment by ctwhome** [comment]
A plugin is being currently in development. 

e have explored different options for displaying the RSD data in WordPress, such as embedding the website directly into the corporate website ([example here](https://www.esciencecenter.nl/rsd/)), using third-party plugins (implementation [here](https://rsd.ctwhome.com/rsd/) and [here](https://rsd.ctwhome.com/software/)), and our preferred choice: developing our own WordPress Plugin. I have started with the base plugin implementation ([see repository](https://github.com/research-software-directory/wordpress-plugin)), so we can add or modify anything in the interface later on based on your feedback.

### Software page
![WordPress Plugin - software page](https://user-images.githubusercontent.com/4195550/215798195-880db128-3f77-426d-bf39-cd1658e52cd7.jpg)

### Projects page
![WordPress Plugin Projects](https://user-images.githubusercontent.com/4195550/215798203-e3ad609b-ad21-40f9-b7f0-b05f950a9599.jpg)

**Comment by ewan-escience** [comment]
Implemented in https://github.com/research-software-directory/rsd-wordpress
