### ISSUE TITLE
 Figure out if / how we move the NARCIS link from the legacy RSD to the new one

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#491]

**Comment by ewan-escience** [comment]
We should have look at:
* https://www.narcis.nl/inclusion/Language/en
* https://www.narcis.nl/repository/repository/RSD-NLeSC/Language/en
* https://harvester.dans.knaw.nl/

**Comment by ewan-escience** [comment]
There is a [harvester in the legacy RSD](https://github.com/research-software-directory/research-software-directory/blob/master/harvesting/oaipmh.py) that we might be able to adapt

**Comment by jmaassen** [comment]
In the legacy RSD, [application.py](https://github.com/research-software-directory/research-software-directory/blob/master/frontend/app/application.py), line 337 contains the code to respond to the OAI-PMH call. Depending on the verb that is provided (ListRecords or GetRecord), it either returns the `listrecords.xml` or `record-XXXX.xml` file (where XXXX is a zenodo ID) which are produced by the harverster.

**Comment by ewan-escience** [comment]
The new data is live on Narcis, see https://act.narcis.nl/search/coll/dataset/Language/EN/meta_repositorygroupid/RSD-NLeSC
