### ISSUE TITLE
mutual exclusion of funding and participating organizations

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#498]
I am trying to add the eScience Center and another organization as funding organizations and participating organizations.

First, I add the organizations as funding organizations, I can save the project page and it works fine. But as soon as i add them to participating organizations, they disappear from the funding organizations part and appear only in participating organization part.

Since the eScience Center is both, we literally need that on all of our project pages.

Just in case, I am trying to edit the PADRE project page (https://research-software-directory.org/projects/the-petaflop-aartfaac-data-reduction-engine-padre) which was imported from the old RSD. But probably the same issue is with the newly created RSD project pages.

**Comment by jmaassen** [comment]
This is a bug. Will be fixed soon.
