### ISSUE TITLE
Editing a link to an existing code repository

### ISSUE THREAD

**Issue by HannoSpreeuw** [research-software-directory/RSD-as-a-service#500]
I tried to edit a link to an existing code repository, because it was actually pointing to an organisation, not a repository.
So I extended the link with `/tkp`. 
I pressed `Save` and `View` but clicking on the `Code repository` link still points to the organisation, not the repository.

You can apparently get it working by first removing the complete `Code repository` entry and then reentering it, but this seems unnecessarily cumbersome.

**Comment by ewan-escience** [comment]
This is not our intention, so that would be a bug. However, we just updated to a new version and I cannot reproduce it. Maybe it was already fixed by accident. Can you test it out again and report here?

**Comment by HannoSpreeuw** [comment]
Okay, just checked.  Still does not work.

**Comment by HannoSpreeuw** [comment]
![afbeelding](https://user-images.githubusercontent.com/11661087/188115714-13a986ed-335f-4998-a648-bc687ff8ef9b.png)

Just changed those three letters `tkp` to `pyse`, just to test.

Clicked on `Save` and `View`, clicked the `Code repository` link again, still points to `tkp`.

**Comment by ewan-escience** [comment]
So this happens on the project edit page. The *first time only*, when changing a project link text or url, the frontend doesn't make a request to the `url_for_project` API endpoint. On subsequent edits and saves, they do happen.
