### ISSUE TITLE
Seeing journal articles requires clicking on the drop-down button

### ISSUE THREAD

**Issue by HannoSpreeuw** [research-software-directory/RSD-as-a-service#501]
In editing mode, when I click on output, to see the output of a certain project, it says 
```
Output                                                                                                     1 
```

So there is one journal article from this project, but it only appears when you click on the drop-down button.

Is this intentionally, why not show at least the top 3 or so?

Not a big issue, but at first sight it seems that this project yielded zero publications.

**Comment by ewan-escience** [comment]
Thanks for the feedback and sorry for the late reply. Maybe this was for an older design, but we think the current design is clear. Each type of mention has a number indicating how many of them there are, and we only show types of which at least one exists.
