### ISSUE TITLE
Show intermediate results when searching for a publication

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#512]
When searching for a publication, i.e. a mention for software or impact or output for a project, three databases are being queried (the RSD, DataCite and Crossref). The search modal doesn't show any results until the all three of these queries are resolved. This is a problem when one of these queries is very slow or doesn't resolve at all. Therefore it would help to show results as soon as one of the queries resolves.

**Comment by bakhshir** [comment]
On the related note, if i put full DOI url, the query does not resolve either. One can just check for `http://dx.doi.org` in the input field and drop it if needed.

**Comment by ewan-escience** [comment]
Another problem: when searching for some term and then changing the search term, it doesn't start the new search (and cancel the old search) when the old search hasn't finished yet. It waits for the old search to fully complete before starting a search with the new term.

**Comment by ewan-escience** [comment]
> On the related note, if i put full DOI url, the query does not resolve either. One can just check for `http://dx.doi.org` in the input field and drop this prefix if needed.

Good point, we'll add support for this as well. 

By the way, quoting from the [DOI website](https://www.doi.org/factsheets/DOIProxy.html):
> The proxy service (both doi.org and the earlier but no longer preferred dx.doi.org)

you should not use the `dx` prefix anymore (but we'll support it anyway).

**Comment by bakhshir** [comment]
> you should not use the dx prefix anymore (but we'll support it anyway).
ah, good to know

**Comment by dmijatovic** [comment]
I might have additional improvement to mentions search feature. When mention is added to RSD from crossref or datacite first time, during the next attempt the RSD entry will be shown first (higher in the list) but the same entry will also be shown as crossref/datacite source. In case the user selects crossref/datacite entry whic is already in RSD the errors will be shown about existing RSD entry. We should somehow ensure that this mention is added to software/project. We could only show RSD entry in this or "silently" ignore error and add existing RSD enrty to software/project. 

My preference would be to show only RSD entry to user, but I am worried that this might be confusing to user.

**Comment by ewan-escience** [comment]
> On the related note, if i put full DOI url, the query does not resolve either. One can just check for `http://dx.doi.org` in the input field and drop this prefix if needed.

This is resolved in #521. The other points of this issue are harder than it seems, so we'll look into those later.

**Comment by ctwhome** [comment]
There are two possible solutions. One is to load results that are available and add new results when the other APIs are resolved. This option could create confusion in the results as they might change without any notice. 
A second option, for now, is to be able for the user to select which API is being queried and give visual feedback on the state.
See the image below:
![image](https://user-images.githubusercontent.com/4195550/191009131-e5d842a7-a547-4cf1-a370-94fa3c0c27cd.png)
