### ISSUE TITLE
Add type for MSc thesis

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#513]
Feedback from @bakhshir : some projects result in a MSc thesis. We support PhD thesis as an output type, but not MSc? 

Same is probably true for BSc?

**Comment by jmaassen** [comment]
Also see #514

**Comment by bakhshir** [comment]
there is only type "Thesis", which makes me think of PhD thesis. Bibtex has separate masterthesis and phdthesis types. As i proposed in the other issue, we could just add an extra field to add this information. Just an advise.
