### ISSUE TITLE
project pages: note field for "other" type of output

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#514]
I am trying to add output to one of our projects' RSD page. The LA reports MSc thesis as one of the output, and indeed thesis acknowledges the funding. I am trying to add this MSc thesis as Other output ("thesis" type) but I am missing note field to add extra information (that this is not phd thesis, but msc thesis). The item does not have DOI.

Could you please add non-mandatory "note" field to the input form for the items without DOI?

**Comment by jmaassen** [comment]
Also see #513

**Comment by bakhshir** [comment]
In fact, Pablo also had issues adding output to RSD project page, because other type of output was still too restrictive.

**Comment by bakhshir** [comment]
We also need such an extra "note" field to distinguish between oral and poster presentation. Otherwise, it become very adventurous where to stick in that important meta-data.
