### ISSUE TITLE
After signing in, the cookies banner is shown again

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#517]
Not sure if this is expected behavior, but when running a local RSD, I get the cookie banner, accept it, sign in, and get the cookie banner again.

**Comment by bakhshir** [comment]
I had the same.

**Comment by bakhshir** [comment]
And now it got worse. It is showing up at every (re)load of a page.

**Comment by dmijatovic** [comment]
@bakhshir It looks like you have cookie blocker running. We are looking at the options to store this information in a different way. Until then you could allow cookies for specific domain (https://research-software-directory.org) in your browser.

**Comment by dmijatovic** [comment]
Closing this issue as it is solved by #566
