### ISSUE TITLE
General responsive layout breakpoints

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#525]
Large screen width layouts make it difficult to read the content presented. It is a common practice to limit the size of the width to 1280px for content and 1920px for applications like dashboards.

The current version of the RSD defaults to 1536px, which makes the content just too wide to be easily readable and accessible. It will be wise to limit the max-width to 1280px and let other elements of the interface like the header and footer to grow to the full wich of the browser window.

![image](https://user-images.githubusercontent.com/4195550/190337890-e66b3bdd-49cc-4e29-84ed-0e39c03df405.png)

**Comment by ewan-escience** [comment]
Thanks for the suggestion. We have discussed this and have decided that we are happy with the current layout.
