### ISSUE TITLE
Filters layout for software page

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#526]
Will fix: #385 #525 

Create filter options for searching and filtering software.

Tasks: 

- [ ] Adap styles as much as possible to match the general RSD branding
- [ ] Design filters (Figma)
- [ ] Implementation

**Comment by jmaassen** [comment]
We should evaluate how well the current filtering works? It has improved a lot over the last few months

**Comment by ctwhome** [comment]
implemented
