### ISSUE TITLE
Be able to search software inside the markdown files

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#527]
See [https://github.com/research-software-directory/RSD-as-a-service/issues/385#issuecomment-1247699862](https://github.com/research-software-directory/RSD-as-a-service/issues/385#issuecomment-1247699862)

Tasks: 

*   [ ] A script that copies a version of the remote markdown files in our DB to be able to index it for searching
*   [ ] Create a cronjob that runs every X times to update the remote markdown content

**Comment by Normo** [comment]
@jmaassen @ctwhome 

Maybe this can be split up into two separate issues: First, implement it for manually written markdown descriptions (that are not loaded from a remote URL) as this seems easier at first view, and second the implementation for remote markdown files. What do you think?
