### ISSUE TITLE
Importing mentions without DOI from file?

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#528]
Adding mentions without a DOI can be quite a bit of work. I got a request from Ben if it would be possible to automate this somehow if the mentions are already in a well defined format. For example, he has a list of presentations in Zotero and a .bib, and would like to add them to a project. 

Maybe we could add a feature to import a mention from a local file? Or have some stand alone tool that does this?

**Comment by ewan-escience** [comment]
We haven't gotten any more requests for this, so we're going to close this issue. If more people want this, we might reopen it. It is also possible to [add mentions in bulk](https://research-software-directory.org/documentation/users/adding-software/#related-output) that have a DOI.
