### ISSUE TITLE
Ambiguous searching box when moving from organizations to software belonging to that organization

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#536]
Based on feedback from @LourensVeen 

The searching box for an organization on the Organization page and the searching box for the software of an organization is placed in the same position, suggesting that both search boxes will do the same but they are completely different.

When going inside an organization both search boxes are placed in the same position:  
![ambiguous](https://user-images.githubusercontent.com/4195550/191764982-1854b0cc-c430-4d0c-87b0-507e10cedb7d.gif)

Since the search for software of projects are at the same level that the organization, it suggested that at least that search box will filter organizations, but instead it searches for software of projects. There is an overlap of context:

![image](https://user-images.githubusercontent.com/4195550/191766249-df0e4d36-9a18-4c22-b425-08478c72e24b.png)

**Comment by LourensVeen** [comment]
Ah, so the second search actually searches *within* the Organisation? That was completely unobvious to me as well. I thought it would do a site-wide search.

**Comment by dmijatovic** [comment]
Maybe we should improve the message shown in the second search box? Instead of "Search for software" we could use "Search for software within the organisation". Note that when you select the projects (menu on the left side), the search will show the message "Search for projects", this should also be adapted to "Search for projects within the organisation". So the (second) search is narrowed to the context of the organisation page. For "global" search user can still use the search box at the top to search for software, projects or organisations.

**Comment by ctwhome** [comment]
Changing the search message would not trigger the user to re-read the input again, although it can be a good addition. Users don't revisit the elements that are already known to them; in this case, the search box had a different context and different functionality, but it is presented in the exact same place.

To create different levels of hierarchy and separation of context we need to enclose the layout creating clear boundaries between what is the organization and what is inside. See the mockup bellow
![image](https://user-images.githubusercontent.com/4195550/191813450-fed208d0-e179-4e75-9dfa-3468c9b644de.png)

**Comment by dmijatovic** [comment]
@ctwhome Maybe we can make it more clear what search does by moving the searchbox down, like in the example below. This would be fairly simple to implement in the current layout/codebase.

![image](https://user-images.githubusercontent.com/9204081/192782377-3d78aa63-4cd7-4eb9-a8cb-5c554dea377d.png)

**Comment by ctwhome** [comment]
It looks good! I would put the image of the organization on top of the left
menu as well!
