### ISSUE TITLE
Low quality header image for DIANNA project

### ISSUE THREAD

**Issue by elboyran** [research-software-directory/RSD-as-a-service#554]
The header image for the [DIANNA project page](https://research-software-directory.org/projects/dianna) is of very low quality (or it does not render well). The image I've upload a while ago in the old RSD was fine.

**Comment by ewan-escience** [comment]
You can store bigger images. There is one on your own [blog post](https://blog.esciencecenter.nl/how-to-find-your-artificial-intelligence-explainer-dbb1ac608009) that you can use. After you save it, do a hard refresh on your browser (Ctrl+Shift+R or similar) to see the updated image.

**Comment by jmaassen** [comment]
We've looked into this issue and it turns out that the images in the old RSD had very low resolution. This wasn't visible on the old project pages, as the image was also showed very small on the old project page. In the new RSD it is blown up to fill the width of the page and therefore the low resolution is clearly visible. 

We should fix this with replacing the images.

**Comment by elboyran** [comment]
Is this resolution enough?

[DIANNA image on corporate site](https://www.esciencecenter.nl/wp-content/uploads/2021/09/shutterstock_680929729-1536x1024.jpg)

Who can/should fix the image by replacing it?

**Comment by ewan-escience** [comment]
That would be more than sufficient. :) @elboyran I sent you an invitation to become a maintainer of the DIANNA project on 3 October. If you are a maintainer, you can replace the picture.

**Comment by elboyran** [comment]
Rena has also sent me a link today. I always clock those ;-). Let's see if I can manage...

**Comment by elboyran** [comment]
@ewan-escience , could you, please, send me the link to the (new) RSD admin page? Sorry, I cannot find it in my emails (easily), the old one does not work of course.

**Comment by elboyran** [comment]
[Done](https://research-software-directory.org/projects/dianna)!
