### ISSUE TITLE
Add links to package managers to software page?

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#555]
Most of the software in the RSD is available in various package managers, like npm, pypi, maven, cran, conda, etc. We should be able to add links to these locations on the software pages, as this is the preferred way for "normal users" to install the software. 

If these links are added, we can also harvest extra information from these packages managers which we need for impact (for example, downloads, views, stars, #used as dependencies, etc.)

**Comment by ewan-escience** [comment]
We want to add a link to a Docker repo.
