### ISSUE TITLE
Improve UX when creating a new project/software

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#564]
When creating a new project or software, the Save button is disabled before any data was entered. After adding a title, the save button is activated although the required description is not entered yet. When clicking the save button, the user receives a message about database constraints:

![image](https://user-images.githubusercontent.com/14222414/194029582-1cfb3523-5343-42c4-9bb8-1e9bb0d92109.png)

My suggestion is to activate the save button only when the constraints from both input fields are met.

**Comment by ctwhome** [comment]
I would also suggest to lead the description as an optional field like GitHub does, to remove any friction when creating a software

**Comment by ctwhome** [comment]
We should reopen this issue since the button still is disabled
