### ISSUE TITLE
cannot add paper

### ISSUE THREAD

**Issue by RvanNieuwpoort** [research-software-directory/RSD-as-a-service#568]
On the new project page, when adding a paper as output, I get this:

![image](https://user-images.githubusercontent.com/1712677/194400592-998136ba-e05c-4f80-9df9-06b990ed4a34.png)

This is a paper I first accidentally added as impact, removed it there, and now want to add again as output.

**Comment by ewan-escience** [comment]
Which project and what is the DOI of the paper?

**Comment by RvanNieuwpoort** [comment]
[project EDL](https://research-software-directory.org/projects/efficient-deep-learning).

I din't use a DOI; I did a title search on "Nearest Neighbours Improves Novelty Detection in Autoencoders", and then select the second entry in the list.

**Comment by RvanNieuwpoort** [comment]
Searching and adding the paper with the DOI indeed works.
