### ISSUE TITLE
Button color missing

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#572]
# MUI buttons - background color removed in build version

![image](https://user-images.githubusercontent.com/9204081/194841556-b00bbbac-3cd7-441d-b4c9-8c0013e1e79a.png)

The button color seem to be removed by tailwind (I think overwrites). 
**NOTE! This occurs only in the "production" version. It is not present/visible in "development".**

![image](https://user-images.githubusercontent.com/9204081/194842089-1ab1309b-3f79-49a5-ba75-8c549909a73c.png)

**Comment by dmijatovic** [comment]
@ctwhome Is it possible to dissable this tailwind overwrite?

**Comment by ctwhome** [comment]
I couldn't find any class with bg-transparent applied to buttons, maybe it is coming from somewhere else?
