### ISSUE TITLE
Adding a DOI doesnt work for strange doi

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#578]
I have problems adding this DOI: https://doi.org/10.1175/1520-0469(2003)60%3C1201:ALESIS%3E2.0.CO;2
to the DALES project.
It appears to be hanging while trying to validate it.

**Comment by dmijatovic** [comment]
@jiskattema, it seem to be encoded url value, which we did not account for in our validations and need to include in the future. 

Quick solution (before we add support for encoded urls) is to use "decoded" value, for this DOI "decoded" value is
`https://doi.org/10.1175/1520-0469(2003)60<1201:ALESIS>2.0.CO;2`
