### ISSUE TITLE
Backend updates

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#588]
There have been some major updates of the backend software/dependencies we use: 

- PostgreSQL 15 ([announcement](https://www.postgresql.org/about/news/postgresql-15-released-2526/), [release notes](https://www.postgresql.org/docs/15/release-15.html), [Docker](https://hub.docker.com/layers/library/postgres/15.0/images/sha256-b1e2423776b4acc769a18e6a166e6103b22575be1d2ff2ae1b55500a5298b2d4))
- PostgREST 10.0.0 ([release notes](https://postgrest.org/en/stable/releases/v10.0.0.html), [Docker](https://hub.docker.com/layers/postgrest/postgrest/v10.0.0/images/sha256-080b61c2e9d78ea473353419f07788114835e46ae5ae93c0e2b532a011d3ad49), [Docker](https://hub.docker.com/layers/postgrest/postgrest/v10.0.0.20221011/images/sha256-3697575a56cc09460b4d212c78c799304f97640eb6bb3edbc16959b2546b16fa)) (done in #590)
- Javalin 5.0 and 5.1.0 ([announcement 5.0](https://javalin.io/news/javalin-5.0.0-stable.html), [announcement 5.1.0](https://javalin.io/news/2022/10/16/javalin-5.1.0-released.html), [migration guide](https://javalin.io/migration-guide-javalin-4-to-5)) (done in #602)
- Java JWT 4.0.0, 4.1.0 and 4.2.0 ([migration guide](https://github.com/auth0/java-jwt/blob/master/MIGRATION_GUIDE.md), [releases](https://github.com/auth0/java-jwt/releases)) (done in #602)

We should look into if and how to upgrade.

**Comment by ewan-escience** [comment]
Upgrading to PostgreSQL 15 might be too risky without concrete benefits, but we could upgrade from version 14.2 to [version 14.6](https://www.postgresql.org/docs/14/release-14-6.html) instead.

**Comment by jmaassen** [comment]
Mostly done. Close for now
