### ISSUE TITLE
[BUG] Updated doi not shown on page

### ISSUE THREAD

**Issue by dsmits** [research-software-directory/RSD-as-a-service#591]
I just updated the DOI for [vantage6](https://research-software-directory.org/software/vantage6) from 10.5281/zenodo.3750881 to 10.5281/zenodo.7221216.

This new doi is showing up in the editor, however, the main page shows the old DOI.

DOI in editor:
![Selection_214](https://user-images.githubusercontent.com/131889/196631514-a9e8bba5-cb8d-403f-96a4-16145d2bb8ae.png)

DOI on main page:
![Selection_213](https://user-images.githubusercontent.com/131889/196631562-67a9e2bc-c122-4bed-bf00-10be3dc1e8e6.png)

**Comment by ewan-escience** [comment]
But now it is. :) When you change it, it does not show up yet, because the scraper hasn't run yet. Note that we don't show the concept DOI there, but only version DOIs, which is what the scraper collects.

**Comment by dsmits** [comment]
I see it now, thanks!
