### ISSUE TITLE
When adding software, I cannot enter a dash into the URL/slug 

### ISSUE THREAD

**Issue by BSchilperoort** [research-software-directory/RSD-as-a-service#595]
On the following page: https://research-software-directory.org/software/add

When trying to add a dash `-` to the URL/slug, like the description says is allowed, no character shows up.

**Comment by ewan-escience** [comment]
In the database, we don't allow a slug to end with a dash. This is translated in the frontend also not allowing a dash at the end. This is of course not how you would like to enter a slug, but as a workaround, you *can* add a dash between two letters.
