### ISSUE TITLE
Duplicate `python` keyword suggestion.

### ISSUE THREAD

**Issue by BSchilperoort** [research-software-directory/RSD-as-a-service#597]
When adding keywords, and typing "pyth...", suggestions come up. However, Python is listed twice:
![image](https://user-images.githubusercontent.com/12114825/196945274-7ad28d65-b596-40cb-acc7-e60b0226d5ff.png)

**Comment by ewan-escience** [comment]
One of them is saved in the database with a trailing space (i.e. `python `). I will try to see if I can fix this in the database for now. 

We should maybe not allow leading and trailing white space in the database.

**Comment by ewan-escience** [comment]
I deleted the duplicate in the database. I will keep this issue open as we should enforce no leading/trailing whitespace for keywords in the database.
