### ISSUE TITLE
Introduce concept of "communities"

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#616]
During the discussions with the TDDC NES, the idea was suggested for the RSD to support "communities". 

A community would be a "virtual organization" where are group of people can curate the set of software and project that are interesting to them. By directly linking to a community (for example: research-software-directory/community/ocean-modelling) it would become easier for user groups to find the software and projects they are interested in.

**Comment by ctwhome** [comment]
Maybe we should leave out this issue from the V2? as it adds a new functionality when the v2 it is a general overall UI revamp and usability fixes

**Comment by maaikedj** [comment]
We moved it to the nice to have milestone because it needs more discussion. It is related to issues #741 that Helmholtz is working on, see above. As discussed in the weekly of 8 May we can take this approach.

**Comment by jmaassen** [comment]
We had a brainstorm in this topic. These are the notes: 

At the moment we have 4 projects who are interested in communities: 

- ModelPlaza (Agent based modelling for archeology)
- TDCC-NES (Natural and engineering competence center in NL)
- ESCAPE-OSSR (The European Science Cluster of Astronomy & Particle Physics)
- EVERSE (includes ESCAPE)

Main idea of communities feature:

- shows software collection of specific research community
   - own logo 
   - own description
   - own software collection
   - own categories + filters
   - for now: 
       - no sub communities, always single entities
       - no projects
       - no organizations

- community has its own maintainers
   - maintainer can define and curate custom categories for community software
   - maintainer decides which categories are mandatory or optional
   - maintainer decides which software to accept into community

- top level item 
   - add "communities" to "software / projects / organizations" list
   - overview page at research.software/communities
      - requires a new "communities" panel 
   - RSD maintainer should be able to add communities
 
To add software to a community, a user would need to: 
- add the software as usual 
- select the relevant community in the software maintainer view
- select the relevant (mandatory/optional) categories   
- note: keywords can be added as usual, still free text

Next, the community maintainer needs to be notified of the pending software, check if it adheres to requirements, and accept or reject it (with message?)

Communities may potentially have a source to harvest information from: 
- 4TU for TDCC NES
- Zenodo for OSSR 

This may require some extra thinking. How to we define custom scrapers? How do you ensure the scraped metadata and mandatory categories match? etc.

**Comment by jmaassen** [comment]
Also allow automatic accept to community? This would allow all helmholtz software to automatically be added to this community.

**Comment by jmaassen** [comment]
The categories should be finished end-april.
