### ISSUE TITLE
Allow uploading logos/images for software projects

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#644]
Allow uploading logos or images for software projects.

The user should be able to select whether the uploaded file is:

1) a logo (everything will be shown)
2) not a logo (user can select which parts of the images will be shown)

We still need to define the aspect ratio for option 2.

**Comment by jmaassen** [comment]
Would it make sense to allow both? And make both optional? That way, we have a bit more information on what the purpose of the image is, and in which cases it can or can not be used.

**Comment by ewan-escience** [comment]
We can postpone putting the images in the grid for now.
