### ISSUE TITLE
projects need more metadata

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#646]
Projects at the moment have a "Grant ID", but we don't do much with that an NLeSC at the moment.
What we do use are 'Project ID's -- is there a way to add a project ID such that we can link a project to our other systems?

**Comment by jmaassen** [comment]
At the moment the "Grant ID" is a generic string which you may use in an organization specific manner. We are not using any standardized Grant ID format yet, although this may change in the future. Many systems (like crossref or OpenAire) use GrantIDs to automatically gather project outputs, something we would also like to automate. 

In the meantime:  what type of project IDs would you like to add? Should these be simple strings, links, something else?

**Comment by jiskattema** [comment]
I was a bit confused about the naming, i thought 'Grant ID' would mean fi. our 'Open eScience Call 2022' and then i would need a project id for 'Project\d+'.
However, we can use the current free-form 'Grant ID' for that. And yes, simple strings (no constraints) would be easiest.

**Comment by jmaassen** [comment]
Seems resolved for now. Reopen if needed
