### ISSUE TITLE
unclear logos on organizational page

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#649]
On https://research-software-directory.org/organisations the eScience Center and Utrecht university have a green-ish checkmark (quite big) next to their name. Why is that?
Clicking on it, or mouse-hovering do not give me extra information.

**Comment by jmaassen** [comment]
These are organizations which are officially registered members of the RSD. They have contacted us to join our effort and have an organization maintainer. 

We'll add an info hover thing to make this more clear.
