### ISSUE TITLE
Organisational units with same names are not distinguishable upon linking

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#651]
When adding organisational units to two organisations, each with the same name (e.g. "Remote sensing") they are not distinguishable when trying to add them to a software:

![image](https://user-images.githubusercontent.com/14222414/201635278-697dbb4c-3b3e-4413-b3bd-81fc1086091e.png)

**Comment by jmaassen** [comment]
This is indeed an issue. Maybe we should somehow include the parent organization in the name? 

Like "eScience Center -> Remote Sensing"

**Comment by cmeessen** [comment]
In my opinion, having to educate the users is not the best choice here, because they wouldn't know that hey have to do this when they enter the name. From a user's point of view, I'd assume I only have to enter the name of the organisational unit. At the moment I would favour to always display the top level organisation instead of the website URL.

**Comment by dmijatovic** [comment]
Thanks for your suggestion. Let's discuss in more detail what we want to achieve and why during the stand up and/or our weekly meetings.

**Comment by jmaassen** [comment]
Another alternative would be to extend the search to show the top level organization + sub level search hits. Something like:

```
Remote Sensing Institiute
General Institute
           --- Remote Sensing Department
General University
           --- Some Faculty  
                     --- Remote Sensing Group
```

**Comment by dmijatovic** [comment]
I was thinking about another alternative :-). We search only in "root" organisations, as ROR does, but when user selects an RSD organisation that has children, we show popup for user to select between root organisation or one or more of the children(s).
