### ISSUE TITLE
Editing pictures of contributers

### ISSUE THREAD

**Issue by elboyran** [research-software-directory/RSD-as-a-service#656]
I could not update my picture in the contributers' list of the [RSD DIANNA software page](https://research-software-directory.org/software/dianna).
Editing the image of the contributor and saving it produced Updated message, but the picture itself was not updated.

**Comment by ewan-escience** [comment]
This could be a caching issue. Did you try a hard refresh? I see on the DIANNA the same picture as the one you use here on GitHub.

**Comment by elboyran** [comment]
Now I see my new picture.
