### ISSUE TITLE
GGIR's author is not working at NLeSc for few years now

### ISSUE THREAD

**Issue by elboyran** [research-software-directory/RSD-as-a-service#667]
Do we want to feature the GGIR software even the first one on the first page?

Moreover, the contact person is given as NLeSc employee.

https://research-software-directory.org/software/ggir

**Comment by jmaassen** [comment]
The software overview page is sorted on mentions at the moment. That is why GGIR is the first entry. We're contemplating other ways of sorting. 

You should keep in mind that this overview shows all data in the RSD, not just the eScience entries. The second entry, parcels, is software from Utrecht University (which the eScience Center has nothing to do with).  

You are right that the contact information for GGIR is out of date. I've discussed this with Vincent and want to invite him to become maintainer again after today's RSD launch. We have other startups who maintain research software interested in joining the RSD.

We've discussed the issue of orphaned / spun-off software in the TechLead meeting last week and it's also related to #647. However, this is more of a procedural / data quality issue than a RSD bug.

**Comment by jmaassen** [comment]
Vincent has taken over the RSD page for GGIR, as owner of the company which now maintains it.
