### ISSUE TITLE
Use more specific Postgres role names

### ISSUE THREAD

**Issue by Normo** [research-software-directory/RSD-as-a-service#673]
In relation to #671 it would be beneficial to either add a `rsd_` pfefix to the Postgres DB role names (e.g. `rsd_web_anon` instead of `web_anon`) or allow custom role names at all.

What do you think?

**Comment by ewan-escience** [comment]
I'm fine with the `rsd_` prefix for the `web_anon` role. I'm not so sure about the custom role names. Do you just want to change the existing three role names or do you want to add more?

**Comment by Normo** [comment]
>  Do you just want to change the existing three role names or do you want to add more?
No, I don't want to add new roles, just change the existing ones.

**Comment by dmijatovic** [comment]
@Normo Are able to make the user change on your own and create PR for us to review?
