### ISSUE TITLE
Add option to ask for agreement to Terms of Service

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#705]
Our data protection lawyer strongly advised us to actively ask for the agreement to the terms of service by users that want to contribute content. We would like to integrate this functionality by asking for agreement, e.g. a check box or an "Agree" button, directly after the first time a user logged into the RSD.

@jmaassen would you be interested in such a feature as well?

**Comment by jmaassen** [comment]
Yes, good idea!
