### ISSUE TITLE
Adding trained models to RSD (as project output or software mentions)

### ISSUE THREAD

**Issue by elboyran** [research-software-directory/RSD-as-a-service#706]
Tried to add a [Zenodo entry](https://zenodo.org/record/7543883) of a trained model to the [DIANNA project](https://research-software-directory.org/projects/dianna) and [software](https://research-software-directory.org/software/dianna) and it did not succeed.

Does RSD support those?

Actually we have several models, see https://zenodo.org/search?page=1&size=20&q=dianna%20model and they are labeled Other in Zenodo, it seems RSD doesn't process that tag?

**Comment by ewan-escience** [comment]
Did you enter the DOI (`10.5281/zenodo.7543883`) instead of the Zenodo URL?

**Comment by elboyran** [comment]
Ah, that works and lists it as **Other**. Maybe you can override as **Model**?

**Comment by ewan-escience** [comment]
All we get back from DataCite is "Other", so we can not distinguish/override this (the scaper would set it back to Other).
