### ISSUE TITLE
Organisation page improvements

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#720]
After introducing releases and testing with long names few UI improvements are desireable

- Show releases per year instead all releases on one page to reduce "load" on db: 
  - additional rpc should be created for counts per year
  - the boxes with count should be used to navigate
 
- Move search box for software and project from header to page content. From the feedback this position seem to be more clear to users that search functions for the page they are currently on

- Max. length breadcrumb label: For long names the breadcrumb label should be reduced to max. 50 chars(?)

- Extend link to complete item of organisation unit

## Current search position
![MicrosoftTeams-image](https://user-images.githubusercontent.com/9204081/217227497-0805c2f2-3f3d-4633-9d3a-392b4fb29635.png)

## New search position
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/9204081/217227435-684e0cc7-11de-4cdb-9dc1-c6ce8e3cddc4.png)

**Comment by ctwhome** [comment]
I suggest also cutting the text in the breadcrumbs, so they do not extend that much. At some point, they will also be too long depending on the screen's width.

And also I like the new position of the search. It makes more sense for the search to be in the same section of the results 👍.

In summary, I would make the change you propose with the addition of also cutting ellipsis the names in the breadcrumbs bar.
