### ISSUE TITLE
Update organization: new name and logo

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#730]
Hi!
The 'Huygens ING' organization, https://research-software-directory.org/organisations/huygens-ing, apparently has a new name and logo.

![Huygens Instituut_Blue_RGB](https://user-images.githubusercontent.com/5823377/218996246-40ce9eaa-b782-4b5a-a0e4-5df0404d914a.svg)
![Huygens Instituut_Blue_RGB_8x](https://user-images.githubusercontent.com/5823377/218996248-90d876a1-1878-4b7b-80e8-9d33c45503c2.png)

And is called "Huygens Instituut"

I'm not the maintainer of the organization -- how can i get this updated?

**Comment by ewan-escience** [comment]
I just updated it.
