### ISSUE TITLE
Customisable pre-defined category lists

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#741]
We have the following use case at Helmholtz: there exist six different overarching [Research Fields](https://www.helmholtz.de/en/research/research-fields/). Each centre dedicates it's research to at least one of the research fields, and they are important when it comes to reporting, proposals etc. We would like to be able to indicate the Research Field a software or project belongs to in a prominent manner.

This could be fulfilled by adding customisable category lists to the RSD. The lists are maintainable in the frontend by Administrators of an RSD instance, and can be used by any user in the instance. Here are some drafts how it may look like in the RSD:

#### Admin frontend

![image](https://user-images.githubusercontent.com/14222414/220318249-d884daba-1ae2-4cac-ac94-f22787292596.png)

* "Visible per default" indicates whether the category is always shown on the edit page. This will nudge users towards actually using them.

#### Software-edit page sidebar

![image](https://user-images.githubusercontent.com/14222414/220318460-0de603ce-95b0-4a4e-8422-188f201a221b.png)

* Display the categories above the keywords to indicate that they may be more important as they are predefined lists
* If other categories exist, users can add them via a dropdown menu

#### Software page

![image](https://user-images.githubusercontent.com/14222414/220318961-423455b6-8247-4d15-83c7-7847a263c9bb.png)

On the software page, the keywords should be shown above the keywords as well.

Suggestions are welcome

**Comment by ewan-escience** [comment]
Some implementation considerations:
* When making a category mandatory, most existing pages won't have a value yet. Therefore, it is impossible to enforce this in the database. However, we can encourage/enforce this in the frontend whenever a maintainer tries to edit a page.
* If an admin _unchecks_ the `multiple selections allowed` box, what should happen for existing software that already have multiple values? Should we delete all values for that software? Or all but one (but which one, this makes the least sense to me)? Or should we not enforce it in the database but in the frontend only?

**Comment by cmeessen** [comment]
Related to #616

**Comment by dmijatovic** [comment]
I also have some implementation considerations. This section is now on the first page in the right panel (see image). There are ideas to simplify first page by moving all items except Publish and License into a Software metadata page. The idea behind is to link ConceptDOI with the imports. Introducing wizzard is also an alternative. The logo will be moved into the Image page. Thinking about alternative location of this feature might be beneficial.

## Current page info layout

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/b623bcce-a78a-4916-9fea-7690d398b27c)

**Comment by ewan-escience** [comment]
Implemented by #984 and #1227.
