### ISSUE TITLE
Feedback about adding mention via DOI

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#745]
Got some feedback from Ben: 

He was trying to add the following mention by pasting into the RSD: 

https://doi.ieeecomputersociety.org/10.1109/PMBS56514.2022.00010

This failed to find the paper, as we detect the "https://doi.org/" prefix, but no the "https://doi.ieeecomputersociety.org/" one. Apparently IEEE has it's own DOI resolver?

**Comment by dmijatovic** [comment]
Interesting. Search works when using only DOI id: 10.1109/PMBS56514.2022.00010

**Comment by jmaassen** [comment]
We should implement the following decision tree: 

- if the entered data is a DOI it's metadata will be retrieved
   - if this is successful, the result(s) are shown 
   - if this is unsuccessful, the user is notified that no data is found.
- if the entered data is a URL, we will attempt to extract a DOI
   - if this is successful, the DOI's metadata will be retrieved as in step 1
   - if this is unsuccessful, an error is shown 
- if the entered data is neither a DOI nor a URL, it's assumed to be a title which we use for search

**Comment by dmijatovic** [comment]
@jmaassen and @ewan-escience I have remark about the specifications concerning the url processing in the search for publications. 

The URL rule, if the url does not contain DOI we show error is too strict in my opinion. I think it would be better to perform title search. I just checked search for [publication title that contains 'https' on Crossref](https://search.crossref.org/?q=https%3A%2F%2F*&from_ui=yes). There are publications > 100.000 publications having https (url) in the title (see image below or use link).

![image](https://user-images.githubusercontent.com/9204081/229111185-ad6b48ea-5ad6-4893-973b-02a6fd9a83ae.png)
