### ISSUE TITLE
Improve search result order 

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#749]
When typing "xenon" in the search box, the exact match is the last entry to be listed, which is weird. As a result, when I quickly type the name of software + press enter, I usually do not end up where I want to go.

**Comment by ctwhome** [comment]
@ewan-escience  is this something that should be made in the API? or should we add a sort option in the call?

**Comment by ewan-escience** [comment]
We could try something like this: https://stackoverflow.com/questions/45418407/how-to-do-an-exact-match-followed-by-order-by-in-postgresql
