### ISSUE TITLE
Mentions don't show the total number after 99

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#751]
is it there a specific reason to not display the total number? in the case of https://research-software-directory.org/software/ggir
the total number gets hidden after 99
<img width="808" alt="image" src="https://user-images.githubusercontent.com/4195550/221593117-9d737ae5-1669-442c-a304-e4443bdb1ebb.png">

**Comment by dmijatovic** [comment]
The space for the badge is usually limited and the natural positioning is above the label. In this specific case we can increase maximum to 999 or 9999. I think that main purpose of the badge is to indicate if a specific section has lot or few items.

**Comment by ctwhome** [comment]
I think that showing the exact number is very important since it is a metric that people care about. 
99+ can be 100, 200.. or more, but the info gets hidden. i would indeed increase the maximum to 9999 if possible to be sure.

**Comment by jmaassen** [comment]
Since printing "99+" takes as much space as "999" we could at least go that high ;-)
