### ISSUE TITLE
ERROR:  unrecognized configuration parameter "request.jwt.claims"

### ISSUE THREAD

**Issue by Normo** [research-software-directory/RSD-as-a-service#753]
When running the migration script [1.17.0-to-1.17.1.sql](https://github.com/research-software-directory/RSD-production/blob/main/database-migration/migration-scripts/1.17.0-to-1.17.1.sql), I received the following error:
```
ERROR:  unrecognized configuration parameter "request.jwt.claims"
CONTEXT:  SQL statement "SELECT CURRENT_USER <> 'rsd_admin' AND NOT
		(SELECT rolsuper FROM pg_roles WHERE rolname = CURRENT_USER) AND
		(SELECT * FROM user_agreements_stored(uuid(current_setting('request.jwt.claims', FALSE)::json->>'account'))) = FALSE"
PL/pgSQL function check_user_agreement_on_action() line 3 at IF
SQL state: 42704
```

After changing the function [check_user_agreement_on_action()](https://github.com/research-software-directory/RSD-as-a-service/blob/v1.17.1/database/021-create-global-triggers.sql#L15)  by setting the *missing_ok* parameter from `FALSE` to `TRUE` inside the [`current_setting()`](https://www.postgresql.org/docs/current/functions-admin.html), the script now ran without errors. 
```
(SELECT * FROM user_agreements_stored(uuid(current_setting('request.jwt.claims', TRUE)::json->>'account'))) = FALSE
```

**Comment by ewan-escience** [comment]
How exactly did you run the script? As which user?

**Comment by Normo** [comment]
@ewan-escience I applied the migration script via pgAdmin to the database on an external DB host. The error occurred under both Postgres versions `13.8` and `14.5`. I used the database user defined in the environment variable `POSTGRES_USER`, who only has permissions on database `POSTGRES_DB`.

**Comment by ewan-escience** [comment]
Is that user a superuser, i.e. what does `SELECT rolsuper FROM pg_roles WHERE rolname = '<username>';` retrurn when you replace `<username>` with the string stored in `POSTGRES_DB`? We currently assume that the migration is ran as a superuser.

**Comment by Normo** [comment]
The query returns `FALSE`.  which indicates that the user used to run the migration is not a superuser.
Since the database is located on an external database host together with other databases, it is not optimal to work with a superuser. Is there any way to work around it?

**Comment by jmaassen** [comment]
Is there any progress on this?

**Comment by ewan-escience** [comment]
Before you run a migration scripts, can you try running `SET ROLE 'rsd_admin';` first? You can later get your original role for the session back with `RESET ROLE;`

**Comment by ewan-escience** [comment]
Closing this issue now due to inactivity.
