### ISSUE TITLE
Empty "Programming language" info if repo URL has no info on programming languages

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#754]
We have a use case where a software repository does not contain any information about programming languages:

https://git.gfz-potsdam.de/igmas/igmas-releases

In this case, the `Programming language` information in the software entry is empty:

![image](https://user-images.githubusercontent.com/14222414/221876214-5be11700-7a24-40c0-9255-3faca1a38d40.png)

**Comment by dmijatovic** [comment]
@cmeessen Maybe it would be more in line with other variables in this section to show 'None' message instead of not showing complete Programming language(s) section?
