### ISSUE TITLE
Edit profile foto (and other data) from my user account settings

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#758]
Is it possible to edit my data from user settings? I would expect to edit my contributor's details  from my account settings

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/4195550/222392654-a3d88416-53ff-4fd0-a282-c42808d4a417.png">
--- 
<img width="584" alt="image" src="https://user-images.githubusercontent.com/4195550/222394163-40a3b87e-3406-469c-9f77-0b71ab5c44d9.png">

**Comment by ewan-escience** [comment]
Your account is fully separate from contributors/team members, since you can also add contributors that don't have an account, and maintainers of a page could actually not be a contributor/team member.

**Comment by ctwhome** [comment]
would it be possible to make that distinction clear for the user? 
or either be able that if the contributor has an account, then use that information instead?

**Comment by ctwhome** [comment]
We could treat the user account as the main information, and contributors as instances of the user account info, in a way that if the info gets changed on the contributor's page, it only modifies that instance and not the main user account. 

That could give a nice workflow, every time a contributor is added, it will take the info from the user account (if exist) and instantiate it. if in the future that person changes jobs position or organization, the instance won't change, showing that the project was made where and what position the contributor had when developing that project. 
We would even give a visual clue in the contributors page if the information about the contributor in the user account doesn't match, to reflect that that person works on a different place or have a different position

**Comment by ctwhome** [comment]
this issue has been approached differently in #759
