### ISSUE TITLE
Display the commit graph within its own timeframe to avoid blanks

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#761]
Some projects are not updated or were finished years ago. is it an idea to show the graph within its own timeframe?

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/4195550/222404579-5f217b29-08f0-4e14-a0d4-e198ca9793f1.png">

**Comment by jmaassen** [comment]
Won't fix for now.
