### ISSUE TITLE
Feedback from Jisk: overview of quality of pages one maintains

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#764]
I got some feedback from @jiskattema after my demo at the SSH section. 

As a PM, he tries to keep the project pages nicely up-to-date, but given that fact that he is now maintaining 80+ of these, it is difficult to have an overview of what needs to be done where. 

He asked if it would be possible to have some quality indicator for the pages. Something like "your page is 65% complete", and then produce a view that can show this metric for a list of pages he maintains. 

This sounds quite similar to what a tool like fairtally is doing: 

![Screenshot 2023-03-02 at 17-05-50 Fairtally results](https://user-images.githubusercontent.com/1705533/222483951-ef57a29f-fa7f-4c6c-8ce1-b9340ca50619.png)

We could think about a similar approach that allows a user to view a list of the pages they maintain, combined with one or more quality metrics?

**Comment by jiskattema** [comment]
@bakhshir ( Rena ) was doing something similar using the RSD API.

**Comment by bakhshir** [comment]
Following suggestion of @ewan-escience i am just querying RSD for the projects that do not list any funding organizations. In this way, i can manually enrich meta-data of the projects, but the original message above is still true. The metric of completeness of RSD pages would very helpful.

**Comment by bakhshir** [comment]
Regarding metric of completeness, we could check if an RSD page has **no**:

- funding organization;
- team (lead applicant or principle investigator);
- contact person;
- participating organization;
- output;
- keywords;
- research domain;
- start and date dates;

That would give quite a bit of coverage. @jiskattema feel free to comment on this.
