### ISSUE TITLE
Scrape extra data from Git repositories

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#770]
We want to scrape the number of stars, forks, open issue count, contributors and maybe more from Git repositories. 

- On GitHub, we can easily get them from e.g. https://api.github.com/repos/research-software-directory/RSD-as-a-service, search for `stargazers_count`, `forks_count`, `open_issues_count` and visit https://api.github.com/repos/research-software-directory/RSD-as-a-service/contributors for the contributors.
- On GitLab, it does not seem possible to get the counts, but we can get the [contributors](https://docs.gitlab.com/ee/api/repositories.html#contributors).

**Comment by cmeessen** [comment]
It is possible via [`GET /projects/:id`](https://docs.gitlab.com/ee/api/projects.html#get-single-project)

Example from the docs:

```json
{
...
    "readme_url": "https://gitlab.example.com/diaspora/diaspora-client/blob/master/README.md",
    "avatar_url": "https://gitlab.example.com/uploads/project/avatar/4/uploads/avatar.png",
    "forks_count": 0,
    "star_count": 0,
    "last_activity_at": "2022-06-24T17:11:26.841Z",
...
}
```
