### ISSUE TITLE
import output from Zotero to RSD

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#773]
During my recent efforts to enrich RSD meta data, I have noticed that lots of output was not exported from Zotero to (old and now new) RSD. Examples are:

Many core project:
https://research-software-directory.org/projects/a-methodology-and-ecosystem-for-many-core-programming
https://www.zotero.org/groups/1689348/netherlands_escience_center/collections/F3AGU2JC

Dirac:
https://research-software-directory.org/projects/dirac
https://www.zotero.org/groups/1689348/netherlands_escience_center/collections/IN7Q7XDN

Could you guys help out with this issue? It is way too much to input it manually.

Edit: The first example of this issue was Massive point clouds project:
https://research-software-directory.org/projects/massive-point-clouds-for-esciences
https://www.zotero.org/groups/1689348/netherlands_escience_center/collections/3E8ERA2T

I did import manually, but not all and it is really a slow process.

**Comment by jmaassen** [comment]
I discussed this a bit more with @bakhshir and @ewan-escience yesterda. Apparently, there was a lot of information missing in the old RSD which was present in Zotero. We'll try to figure out if we can create a one-time migration script for this data, as checking/migrating it all by hand would be way to much work.

**Comment by ewan-escience** [comment]
I wrote a migration script and ran it today. Everything from Zotero that was selected to be migrated should now be migrated.
