### ISSUE TITLE
Choice for bidirectional "related projects" link

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#788]
Currently, RSD allows us to add related projects to the project pages but this is one directional. Meaning if I want to add on the project B page link to the related project A, B will not get that link automatically. I will have to add manually link to the project B page the link to project A. This is potentially problematic because we have a lot of historical projects, and i am not a big fan of manual work.

Could you make these relations bidirectional? I am curious to hear about the cases when such a link has to be one-directional.

**Comment by jmaassen** [comment]
After talking to @bakhshir it's clear that the interpretation of this relation is quite broad: 

- a project is similar (topic / technology / knowledge wise)
- a project is from the same call
- a project has a direct relation (follow-up, predecessor)

In all these cases, adding a bi-directional relation makes sense. We should go for that @ewan-escience
