### ISSUE TITLE
`yarn` should be listed as requirement

### ISSUE THREAD

**Issue by dalonsoa** [research-software-directory/RSD-as-a-service#796]
The Makefile uses of `yarn` to [install a few things](https://github.com/research-software-directory/RSD-as-a-service/blob/ed2f70643d87b0643e54598168da855773d068cd/Makefile#L38) when setting up the system locally following your instructions. However, `yarn` does not seems to be installed by default, at least in MacOS 13.2.1:

```bash
cd frontend && yarn install -d
/bin/sh: yarn: command not found
```

**I would suggest to list that as a requirement in the README and the Documentation.**

The issue is easily solved in MacOS installing `yarn` with `hombrew`:

```bash
brew install yarn
```

**Comment by dalonsoa** [comment]
Happy to take this one.

**Comment by dmijatovic** [comment]
@dalonsoa That would be great! 
We would like to support MacOS and Linux approach.
Let us know if you need more information.
