### ISSUE TITLE
Create styles for the RSD website matching eScience branding

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#81]
The current styles of the website match the old eScience center branding house, We need to find update the overall look and feel of the RSD website with a modern look that resembles the new science Center house branding

**Comment by jmaassen** [comment]
Maaike and I have had some discussion if this is a good idea. Making the style too much "escience center" may cause external organizations to object to adding their software, as it seems it was made by us. That was also the reason we chose a more neutral style for the legacy RSD. 

I would be in favor of sticking to a neutral style for the RSD-as-a-service. Alternatively, we could allow organizations to set their own style on their own pages. This may be more complicated?
