### ISSUE TITLE
Move away from Postman for API tests

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#813]
We should replace the Postman/Newman tests ([here](https://github.com/research-software-directory/RSD-as-a-service/tree/main/backend-postgrest/tests)) with something else, for two reasons:

1. Since February 2023, you can only do 25(!) collection runs per month on a free account ([announcement](https://blog.postman.com/postman-2023-product-and-versioning-updatesand-vs-code-extension/)).
2. The Postman interface is becoming less suitable with the increasing number of tests.

To address the second point, we should go for a full code-based solution. Considering the languages already in use, we should either go for Java or JavaScript/TypeScript.

**Comment by jmaassen** [comment]
Java + junit be an option? (plus some of the libraries needed to spin up dockers). I've got quite a bit of experience with that, and happy to help

**Comment by ewan-escience** [comment]
Two Java libraries that can help with testing the REST part are [REST Assured](https://rest-assured.io/) and [Citrus](https://citrusframework.org/).
