### ISSUE TITLE
Ensure use of theme colors in tailwind classes

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#823]
The default tailwind config file offers more color options than we have defined in our theme. In out html markup there are few places where these non-theme colors are used (home page is one example). 

Using non-theme colors might create undesired theme issue for users of zelf-hosted RSD instances which want to apply their custom colors. 

The color options are shown by tailwind VS code plugin. We  can limit color options by moving `colors` object from `extend` section directly into `theme` section. The approach should reduce use of non-theme colors in tailwind css by their class names. 

In addition to tailwind configuration change we need to ensure (find) all non-theme colors used are added to our theme colors or replaced with an alternative color from our theme. The theme colors are defined in frontend/public/data/settings.json.

**Comment by ctwhome** [comment]
One color that there is not in the variable. Which is a variant of the color gray. We should include it and replace the color where it is being used (new software page).

**Comment by ctwhome** [comment]
I guess this issue can be closed?

**Comment by dmijatovic** [comment]
@ctwhome Currently this is merged into rsd-v2-release branch. I count on github to close it after we merge to main.
