### ISSUE TITLE
Switch to `docker compose` plugin

### ISSUE THREAD

**Issue by fembau** [research-software-directory/RSD-as-a-service#830]
The `docker-compose` command will be deprecated ([source](https://docs.docker.com/compose/install/)):

From the end of June 2023 Compose V1 won’t be supported anymore and will be removed from all Docker Desktop versions.

Make sure you switch to [Compose V2](https://docs.docker.com/compose/compose-file/) with the docker compose CLI plugin or by activating the Use Docker Compose V2 setting in Docker Desktop. For more information, see the [Evolution of Compose](https://docs.docker.com/compose/compose-v2/)

**Comment by ewan-escience** [comment]
If you run Linux Mint, you can mostly follow the Ubuntu instructions [here](https://docs.docker.com/engine/install/ubuntu/), but you need to make one small change: In step 3 of `Set up the repository`, you need to replace `$VERSION_CODENAME` with `$UBUNTU_CODENAME`.
