### ISSUE TITLE
Proper support for OAI-PMH 

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#833]
From the NARCIS/OpenAIRE workshop on 5/4/2023 it became clear that pretty much all research institutes, archives, libraries, etc. use OAI-PMH to exchange data with aggregators. Originally NARCIS would collect all information from NL and pass this on to OpenAIRE, which aggregates at EU level. NARCIS has been discontinued however, so we now need to connect directly to OpenAIRE.

To supply information to NARCIS we only had a rudimentary API. For communication with OpenAIRE however, a proper implementation is needed. 

I would propose to investigate which implementations are available, and how much effort it would be to connect to our DB.

**Comment by jmaassen** [comment]
OAICat seems to be an implementation which is widely used and adapted. There are various mentions and forks of it.
Original implementation: 
- https://github.com/openpreserve/oaicat (Java)
- https://www.oclc.org/research/areas/data-science/oaicat.html
 
Huygens is running its own:
- http://oaipmh.emitx.huygens.knaw.nl/ 

Example tying it to figshare:
- https://github.com/lylewinton/oaicat-figshare (Java)

Alternative implementations:
- https://github.com/pandzel-zz/Demeter (Java)
- https://github.com/folio-org/mod-oai-pmh (Java)
- https://github.com/MyCoRe-Org/oaipmh/ (Java)
- https://github.com/dmj/oai-repository (PHP)
- https://github.com/NatLibFi/melinda-oai-pmh-provider (Javascript)
- https://github.com/SciCatProject/oai-provider-service (TypeScript)
- https://github.com/niklr/OaiPmhNet (.NET)

**Comment by ewan-escience** [comment]
I tried out the [joai-project](https://github.com/NCAR/joai-project). I could not get it working on Tomcat 10.1.7 but I did on Tomcat 8.5.87. 

As can be seen [in the documentation](https://pure.mpg.de/oai/docs/provider.jsp), we need to provide XML files ourselves in a supported format (search for `Providing files in multiple formats`). The most versatile format is `adn`. 

So if we use this library, we need to to the conversion from the data in our database to XML files ourselves. The library will then take care of handling all requests.

**Comment by ewan-escience** [comment]
I quickly tried out the [mod-oai-pmh](https://github.com/folio-org/mod-oai-pmh) project, but it failed to build:

```
Caused by: org.raml.jaxrs.generator.GenerationException: [Include cannot be resolved: /[redacted]/mod-oai-pmh/target/classes/ramls/raml-util/schemas/errors.schema -- /[redacted]/mod-oai-pmh/target/classes/ramls/ [line=12, col=11], Include cannot be resolved: /[redacted]/mod-oai-pmh/target/classes/ramls/raml-util/traits/validation.raml -- /[redacted]/mod-oai-pmh/target/classes/ramls/ [line=15, col=13]]
```

I also couldn't find any documentation on how to actually use it (which is the case for most implementations listed above).

**Comment by ewan-escience** [comment]
OpenAIRE uses the DataCite metadata format (prefix `openaire_data`) [[1]](https://guidelines.openaire.eu/en/latest/data/use_of_oai_pmh.html) [[2]](https://schema.datacite.org/meta/kernel-3/index.html) [[3]](https://schema.datacite.org/meta/kernel-3/metadata.xsd). The [joai-project](https://github.com/NCAR/joai-project) does not support this format by default, so we'd have to write our own converter [[4]](https://pure.mpg.de/oai/docs/provider.jsp#convertors).

Furthermore, OpenAIRE, uses version 3.1 of the schema [[5]](https://guidelines.openaire.eu/en/latest/data/application_profile.html), even though the most recent version is [4.4](https://schema.datacite.org/meta/kernel-4.4/). Furthermore, they made some changes to the schema, mostly by making more fields mandatory.

**Comment by ewan-escience** [comment]
I just created an account at OpenAIRE Provide. They don't support software repositories yet, see the screenshot. 

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/91328544/fbd8073a-7b76-4951-b68a-27302ff00ac7)

@jmaassen you earlier linked to https://guidelines.openaire.eu/en/latest/data/use_of_oai_pmh.html, but don't you think https://software-guidelines.readthedocs.io/en/latest/application_profile.html would fit better when it becomes available? So should we wait until that becomes available or try to make an OAI-PMH endpoint available with metadata that satisfies the format of the first link?

**Comment by ewan-escience** [comment]
Since we are now [visible as a source on OpenAIRE](https://netherlands.openaire.eu/search/advanced/research-outcomes?type=software&qf=false&sortBy=resultdateofacceptance,descending&resulthostingdatasource=%22fairsharing_%253A%253A1a77befc3b608d6ed363567685f70e1e%257C%257CResearch%2520Software%2520Directory%22), we can consider this to be completed.

For the record, we use the [joai-project](https://github.com/NCAR/joai-project) as the OAI-PMH server ([hosted here](https://oai.research-software-directory.org/oai/)) and wrote a [simple Java program](https://github.com/research-software-directory/rsd-oai-pmh) that generates the XML files.
