### ISSUE TITLE
RSD ORCID search issues

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#837]
The issue has been a while now: the ORCID search bar on the RSD edit page sometimes does not yield the same results as searching on the ORCID website directly. Example, I tried to add today `Gianluca Tirimbo` to a project team and her name did not show up as a search result. Instead I looked her up first on ORCID, found her ID immediately as a first result, and then added her via ORCID ID.

Could it be some whitespaces problem?

**Comment by ewan-escience** [comment]
Do you mean `Gianluca Tirimbò`, notice the accent on the `ò`? If you would have searched for that instead, you would have found her. This is just how the ORCID API behaves, so I don't think there is anything we can do about it. Do you have other examples where special characters cannot be the issue?

**Comment by ewan-escience** [comment]
It seems that we can get better results using the [Fuzzy Searches](https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-FuzzySearches). Compare e.g. https://pub.orcid.org/v3.0/expanded-search/?q=given-names:Gianluca+AND+family-name:Tirimbo*&start=0&rows=50 and https://pub.orcid.org/v3.0/expanded-search/?q=given-names:Gianluca+AND+family-name:Tirimbo~*&start=0&rows=50.

It would help if you have more examples @bakhshir. 😀

**Comment by bakhshir** [comment]
I will keep a watch on those cases, and report back in this thread.
