### ISSUE TITLE
SEO sitemaps registration and webmaster tools

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#852]
# SEO - missing software item ricgraph

Initially we had problems with generating the sitemaps for RSD. This problems has been addressed in #723 and the sitemaps are beging created now. Still software item ricgraph, mentioned in issue 723, is not listed in Google search.

## RSD robots.txt and sitemaps setup
- [robots.txt](https://research-software-directory.org/robots.txt)
- [software sitemap](https://research-software-directory.org/sitemap/software.xml)
- [projects sitemap](https://research-software-directory.org/sitemap/projects.xml)

[Google support documentation](https://support.google.com/webmasters/answer/7474347?hl=en) indicates that sitemaps can be manually submitted. After manually submitting sitemap files the following message is shown suggesting to use [webmaster tools](http://www.google.com/webmasters/tools/) to follow the progress.

![image](https://user-images.githubusercontent.com/9204081/233593430-35cada51-fa67-4190-bc5a-1ff9b5c3f1fc.png)

I was able to find number of software items created after ricgraph on Google. This suggests that crawling RSD software items work. For example: 
- [Motrainer](https://www.google.com/search?q=motrainer+site%3Aresearch-software-directory.org)
- [Lilio](https://www.google.com/search?q=lilio+site%3Aresearch-software-directory.org)
- [Cwltool](https://www.google.com/search?q=cwltool+site%3Aresearch-software-directory.org)
- [4cat](https://www.google.com/search?q=4cat+site%3Aresearch-software-directory.org)
- [Pathvisio](https://www.google.com/search?q=pathvisio+site%3Aresearch-software-directory.org)
- [Springtime](https://www.google.com/search?q=springtime+site%3Aresearch-software-directory.org) which was created 4 days before this search is tried

**Comment by ewan-escience** [comment]
As can be seen from the screenshot, Ricgraph is indexed by Google, so it remains unclear why searching for `site:https://research-software-directory.org/software/ricgraph` on Google yields no results...

![Screenshot_2023-06-12_14-43-54](https://github.com/research-software-directory/RSD-as-a-service/assets/91328544/f19043d9-a55e-4886-aa58-838b51b14949)

**Comment by ewan-escience** [comment]
When I now search for `ricgraph site:research-software-directory.org` on Google ([link](https://www.google.com/search?q=ricgraph+site%3Aresearch-software-directory.org)), the Ricgraph page is shown.
