### ISSUE TITLE
No About section to be found in the organisation settings

### ISSUE THREAD

**Issue by tpronk** [research-software-directory/RSD-as-a-service#855]
On the [About](https://research-software-directory.org/organisations/amsterdam-university-medical-centers?page=about) page in the area where I can manage my organisation, it says "To activate the about section, add content to the about section in the settings.". However, if I go to the [settings](https://research-software-directory.org/organisations/amsterdam-university-medical-centers?page=settings), I can't find any "About" section.

NB. I'm using Chrome 112

**Comment by dmijatovic** [comment]
@tpronk Thanks for your feedback. 

The about page is not required. However, if you would like to use it, you can provide the information in the markdown format at the settings page in the About page section. In the printscreen below I point to section where text can be provided. Can you conform that you see About page section in the settings?

![image](https://user-images.githubusercontent.com/9204081/234338925-4ee0ebbd-6b70-47b8-98ea-7b5febea2f88.png)

I would also appreciate some suggestions on how we can improve message shown in about page :-).

**Comment by ewan-escience** [comment]
You actually don't get to see the same in the screenshot when you're an organisation maintainer. Only admins get to see that part. So this is a bug we have to fix. 

Furthermore, the organisation page gets very slow when you're a maintainer of that page.

**Comment by tpronk** [comment]
Thanks! I'll wait a while until a new version is up and then go play with the "About" section again
