### ISSUE TITLE
Contributor Profile page

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#879]
We can currently see the contributions of a user based on their ORCID. 
The idea of this issue is to create a link to a place, we could call it "Contributor Profile" where we display all the software and projects that users are participating

The ORCID id should not be clickable here but inside the new Contributor Page

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/e521f31c-39b4-4d3d-b1c9-fee447988453)

These 2 queries bring the list of contribution filters projects and software by ORCID (Thanks @ewan-escience)
https://research-software-directory.org/api/v1/contributor?orcid=eq.0000-0002-2170-3253&select=given_names,family_names,software(slug,brand_name)

https://research-software-directory.org/api/v1/team_member?orcid=eq.0000-0002-2170-3253&select=given_names,family_names,project(slug,title)

Note: there is currently no design for the Contributor profile page. We might add something quick and improve it later?

**Comment by ewan-escience** [comment]
If in addition, we add an `orcid` field to the `account` table in the database, that you can edit in the frontend, we can create a quick link that shows your contributions from e.g. the avatar dropdown, so you don't have to find a software or project page first where you have contributed.
