### ISSUE TITLE
Markdown code formatting (via backticks) also shows the backticks

### ISSUE THREAD

**Issue by tpronk** [research-software-directory/RSD-as-a-service#899]
In the README.md of a code repo I added to the RSD, I use backticks (`) to format code. At the RSD the code is indeed rendered as I expected, but the backticks themselves are also included. https://research-software-directory.org/software/splithalfr

**Comment by dmijatovic** [comment]
@tpronk Thanks for creating the issue. We use react-markdown library for the markdown support. I will investigate it and come back to you early next week latest.
