### ISSUE TITLE
Position correctly the highlights card on window resize

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#916]
The current carousel only uses CSS for the complete iteration. However, it is impossible to calculate the distance between the first highlighted card with the left side of the content, which is centered and responsive, only with css.

In this task, i will add the necessary react code to calculate the distance and apply it to the scroll position of the carrousel.

See working example here: https://www.apple.com/store

<img width="1171" alt="image" src="https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/7f2ec684-c686-4320-a47b-5c23a4537a8b">

**Comment by dmijatovic** [comment]
@ctwhome The content uses tailwind container class. Is is possible to enclose cards into `container` class and then start from 0 (relative)?

Alternative could be to have a look at [swiper](https://swiperjs.com/react) use.

Good luck!
