### ISSUE TITLE
Add Status filter in projects page

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#934]
There is currently no filter for Project status. Probably useful for PMs, it could help to have a filter based on Status with the following options (or similar):
- Pending
- In progress
- Finished

See the wireframe idea: 
<img width="1006" alt="image" src="https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/15c30d78-b2e0-40b9-8746-29b9f14c8451">

**Comment by jmaassen** [comment]
Good idea. Maybe use "pending" instead of "not yet started"? 

-

**Comment by dmijatovic** [comment]
I assume, the same filter should be applied on the organisation projects page.
