### ISSUE TITLE
Clear button is enabled when entering the Software and Project pages 

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#937]
When moving routes between Sofware and Projects pages for the first time, the filters bar has enabled the 'Clear' button but the number of filters shows 0.

I guess that the default sorting method should not enable the clear button.

<img width="1256" alt="image" src="https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/3021e58b-1238-4e52-8052-d43f70779341">

**Comment by dmijatovic** [comment]
Clear is enabled because we apply order on mentions. The counter is at 0 because we decided not to count order as a filter. Let see what others think about this approach. Our initial idea is that counting order as a filter could be confusing.

**Comment by ctwhome** [comment]
In any case the clear button shouldn't be enabled at first load. You could remove the 'Order by' from the filters counter, so the sorting doesn't affect the filters counter

**Comment by jmaassen** [comment]
Indeed we could treat filtering and ordering as two separate things.
