### ISSUE TITLE
Alternative design for Verified organizations badge

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#938]
The verified organization's current implementation is very strong. The colored ribbon attracts much attention, stealing protagonism from the logo and the name of the organization. Unless that is the desired effect, we can change the Verified badge into a more familiar and less prominent design, placing it at the bottom right of the card, similar to what we have with the contributors, and mentions icons on the Software cards.

### To illustrate this change, I came up with 3 different icon designs:

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/063922a1-94f1-4f2d-88a6-2114ee796bdb)

One of my favorite designs is number 1, which somehow has a cleaner shape, and it is also round as our RSD logo :)

### Other icons alternative could be: 
![image](https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/bab468c6-a524-4aed-bdd2-5e88755fc76a)

### Tooltip information or popovers
Following again the same example the in the Software card, the verified icon should have a tooltip indicating the label named. Or even a poppi hover with more information and a call to action, something like **Learn more**, or **Claim your organization**
<img width="1606" alt="image" src="https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/116cc4bf-07c9-4f09-88ae-bb59c293e336">

**Comment by jmaassen** [comment]
Very nice! The tooltip also clarifies what the tag means. Would the claim organization go to the same form as 'join as an organization' on the landing page?

**Comment by ctwhome** [comment]
I think so, we could fill in the organization name directly in the form!

**Comment by dmijatovic** [comment]
I like 1 or 3 when organisation is verified. However I think we should have completely different icon for claiming an organisation. Something that calls to action maybe some of these

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/3e150621-7ad4-496f-99d6-8bce45260b88)
![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/3194a7ac-5c72-4d87-89c3-67e6398b38bc)
![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/eab2c66a-fd77-4630-8eb6-70580a6505cf)
![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/69dddb4b-7666-4306-a629-5a5dfebc4ec2)

**Comment by ctwhome** [comment]
the current PR has a centered counter in the card and includes a new icon for unverified organizations. When is this design decision been taken? I am afraid that the PR will be merged and the changes pass without notice.

**Comment by jmaassen** [comment]
The proposed design does not clearly show the difference between a verified an unverified organization. We need a clear distinction between the two, and the meaning should be somewhat intuitive from just looking at the icon. Only showing the difference when you mouse over is not sufficient.  The current choice clearly shows the difference, but I'm fine with improving the icons. 

The off center numbers did not look good in testing, as the card was unbalanced. This may also have been caused by the location of the verified icon though.

**Comment by ctwhome** [comment]
I believe there's room for improvement in the presentation of unverified organizations on the card interface. Labeling an esteemed institution like the University of Amsterdam as "Unverified," for instance, might unintentionally give a negative impression. Visitors could question the credibility, reliability, or competency of the organization, which is far from the intended message. 

The term "Verified Organization" is also somewhat ambiguous without context. It's not clearly defined on the website for first-time visitors, which might add to the confusion. Perhaps we could consider not displaying an icon for unverified organizations, while featuring those that are verified in a more prominent manner.

For improving user understanding, one idea could be to introduce a page-level banner that briefly explains what it means for an organization to be verified within the Research Software Directory. Alternatively, a more detailed popover could serve this purpose, though this would require the user to hover over the icon to gain that understanding.

By adopting these measures, we can make the information more transparent and user-friendly.![image](https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/0fa03907-5787-43da-8925-236a9ef680a4)

**Comment by jmaassen** [comment]
Maybe it would make sense to change the terminology? 

The idea is that some organizations have 'joined' the RSD officially, while others are only mentioned because they have participated in the development of some software. 

In theory, we could also show this difference in a different way: a different color for the tiles, two separate lists of organizations (members and non members), etc.
