### ISSUE TITLE
It is possible to make contact person to more than one member in projects

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#948]
To change the contact person of a project, you have to first change the current contact person. 
I would expect that the new contact person switch will disable the previous one by default.
When selecting a new contact person there is no indication or information that now there are 2 contact persons, and it is unsure which one is selected.

To fix: 
- when selecting a contact person, disable the rest in that operation, leaving the new contact person as the only enabled option.

**Comment by ewan-escience** [comment]
Wouldn't it make sense to allow for multiple contact persons and show all of them as such?
