### ISSUE TITLE
Checks for GitHub repository URLs

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#949]
GitHub repository URLs, in contrast to e.g. GitLab, which can be hosted on any domain, have a fixed structure. We should add some checks that prevent (or just give a warning when entering) people from entering wrong GitHub URLs in the frontend, and skip wrong URLs when scraping.

**Comment by ctwhome** [comment]
for example adding https://github.com/ctwhome/SmartPlay/tree/main -> tree/main to the URL won't work for the scrappers as ewan pointed

**Comment by ctwhome** [comment]
it could be possible that a repot specifies a branch in the URL, like tree/main, or tree/beta.
Is it possible to scrape the repos in those cases?

**Comment by ctwhome** [comment]
I labeled this issue as a bug after introducing an unsupported URL repo doesn't trigger the scrapers and also doesn't give any hint to the user

**Comment by ctwhome** [comment]
In that case, it might be wise to add this limitation to the field itself as an information box.
