### ISSUE TITLE
Improve visibility of "Related Projects" in edit view

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#983]
We notice that, when editing their software entries, many users in the Helmholtz RSD create an Organisation for something that would more appropriately be considered as a project.

My guess is that the reason for this is that the user might not be aware that there can be related projects, because it is not immediately apparent on the edit page: the relations are hidden behind the "Related topics" entry. From my perspective, the user might be more aware of these relations if "Related Projects" and "Related Software" would be separate entries in the menu.

**Comment by ctwhome** [comment]
I can see how people used to GitHub use Organizations to wrap repositories. I agree with your statement. Should we plan a design session to come up with a layout alternative?

**Comment by dmijatovic** [comment]
Maybe we can just split the current page in two? That would be relatively quick and easy to implement and should achieve the goal?
